#ifndef GRAMMARQUIZ_H
#define GRAMMARQUIZ_H
#include <QString>

class GrammarQuiz
{
public:
  GrammarQuiz();
  ~GrammarQuiz();
  QString getQuestion(int index);
  QString getChoices(int col,int row);
  char getAnswers(int index);
  QString getDefaultButtonColor();
  QString getRedButtonColor();
  QString getGreenButtonColor();
  QString getLivesBackground();
  QString getQuestionBonusQuiz(int index);
  QString getChoicesBonusQuiz(int col,int row);
  char getAnswerBonusQuiz(int index);
private:
  QString redColorOfButton = "border: 2px solid #555;border-radius: 20px; border-style: outset;padding: 5px; font: 15pt \"Sans Serif\";	color: rgb(255, 255, 255);background-color: rgba(255, 66, 69,190);";
  QString greenColorOfButton = "border: 2px solid #555; border-radius: 20px; border-style: outset;  padding: 5px;  font: 15pt \"Sans Serif\";color: rgb(255, 255, 255);background-color: rgba(43, 255, 68,190);";
  QString defaultcolor = "QPushButton:hover{;background-color: rgba(0,0,0, 120);border: 2px solid #555;border-radius: 15px;border-style: inset;font: 16pt \"Sans Serif\"; color: rgb(255, 255, 255);}QPushButton:!hover{  border: 2px solid #555;border-radius: 20px;border-style: outset;padding: 5px;  font: 15pt \"Sans Serif\";background-color: rgba(0,0,0, 200);}";



  QString livesBackground = "background-repeat:no-repeat;background-image: url(:/bGrounds/backgrounds/h11.png);";
  QString questions[200] = {
   "_______ is better than nothing.",
   "He plants to complete all ______ work soon.",
    "_____ the six boys in the class has finished their homework.",
    "You are the man ______ our professor respects most.",
    "You and I must obey ______ parents.",
    "The jury has given ______ verdict.",
    "______ are those to be imprisoned.",
    "I gave him a book, and _______ was returned to me later.",
    "He is a man ______ I know you can trust completely.",
    "Everyone should try to improve ______.",//10
    "An old farmed had a goose _______ laid a golded egg every day.",
    "Those books are _______",
    "_______ the two students are careless",
    "Many soldiers have met _______ death on the battlefield.",
    "All the students in the class help _______",
    "Both the friends were idle, ____ of then stood up to",
    "Don't buy the expensive apples, get the ______.",
    "My son looks as handsome as ______.",
    "_____ do you think will get the first prize?",
    "_______ to one's country is the duty of a citizen",//20
    "We will complete this construction in two ______ time.",
    "I want to buy some good ______ stationery for the office.",
    "On almost every page, there were ______ for cigarettes and tobacco.",
    "He postponed his _____ going to Delhi.",
    "I was very nervous during the ______, and I'm sure they'll give the job to someone else.",
    "________ is not working.",
    "A/An ______ of ants had formed around the sugar cube.",
    "The _____ of life must be available to all.",
    "There is no danger of the _______.",
    "That _____ is the father of three children.",//30
    "The Indian team defeated the Australian team by an ______.",
    "A woman on her wedding day or just before abd after the event is a _______.",
    "_______ helicopter crashed during the trial.",
    "A _____ of hounds and wolves.",
    "These four songs are his _______.",
    "My son broke ______ toy.",
    "One of my ________ tells me that you are not working correctly.",
    "He was carried away by ______ in the black dress.",
    "Peace has _______ victories no less renowned than war." ,
    "The girl next to me tried to start a ________.",//40
    "A written outline of a film, novel or stage work giving details of the plot and individuals scene is a _______.",
    "____ is also granted to the needy students in our college.",
    "Have you seen my _____ of stamps?",
    "Usually, we do not find ______ driving a public vehicle.",
    "I met _____ yesterday.",
    "The criminal was put in ______.",
    "We have got a room booked at _______.",
    "_______ decision is obviously beneficial to the nation.",
    "Children could spot a _______ of fish in the nearby pond.",
    "A ______ of savages attacked the explorers at night.",//50
    "In my past difficult days, music was a great _______",
    "______ feathers are short.",
    "Sachin has scored more than fifteen ______ runs so far.",
    "The was a ______ at the ______ of my houses.",
    "He looked like a professional wrestler with his muscular ________.",
    "_______ is transitory.",
    "The child has broken ______ left hand.",
    "Is there any ______ in the fridge?",
    "The _____ of accidents is steadily increasing",
    "_______ given to the beggars are sometimes misused.",//60
    "There are ______ in a desert where travellers can take a shelter.",
    "A true ______ is one who keeps one's country's secret to oneself.",
    "The whole army, _______ and ________ were defeated.",
    "A bike has run over a squirrel. ____- still lying onthe road.",
    "His opinion has raised several _______.",
    "The _____ has approved his appoinment.",
    "A young unmarried woman is a ________.",
    "I lived in a forty-_______-old house there.",
    "This is ______ bag.",
    "Mr Chan used a ________ of buffaloes to help him plough his field.",//70,
    "All the ___- of Asia are now up against Pakistan.",
    "The abstract noun of \"young\" is the ______.",
    "The colour of all the ______ in the house has faded with time.",
    "______ is a new house.",
    "I read out all the ______ of his letter to my papa.",
    "The sports _______ makes arrangement for games.",
    "______ are deternube to win the World Cup.",
    "The charater of feeling for others in their position is called ______.",
    "The child is often afraid of its own ______.",
    "I know him. He is a ________.",//80
    "A ______ of sheep and goats were grazing in the field.",
    "It is compulsory to have the _______ of the principal.",
    "What is your verdict, gentleman of the _______?",
    "A ______ is an unmarried mature woman.",
    "The _______ was on old man riding a black horse.",
    "Looking at the world map, we see Japan here ______ is one of the most powerful contries in the world.",
    "The medicine gave him _______ from suffering.",
    "A ______ doctor has been sent.",
    "We suffer from ______ pollution.",
    "There was a _____ in the house.",//90
    "She wants to gain ______ and recognition as an actress.",
    "The ________ saved her husband from death.",
    "Five _____ of partridges were seen in the park.",
    "The moon hid _____ face behind the clouds.",
    "I am going to attend ______.",
    "_____ sight it was!",
    "You are a ________; you do not know the value of savings.",
    "The ability to share someone else's feeling or experience by imagining what it would be like to be in that person's situation is called _______.",
    "I said a ______ of cows in the field.",
    "A _____ of policemen guarded the mosque.",//100
    "The prince punished the duke, who was a _______.",
    "We were amazed at the ______ of the Himalayas.",
    "There are two _______ in my class.",
    "Five thousands _______ were sent to Punjab for border security.",
    "We can't live without",
    "The police were trying to curb the ________.",
    "She cut a piece of cloth with ________.",
    "ALl the _______ he gave us may not be wholly right.",
    "Why did you buy the _____ stove?",
    "She was granted ten _____ leave.",//110
    "My sister is reading _______ of the book.",
    "The monks travelled to _______after ________.",
    "Cleanliness is next to __________",
    "Death always knows _______ victim.",
    "The art of composition of poetry is _______.",
    "There are many beautiful natural _______ that charm us.",
    "There are _______ in everyone's life.",
    "Andrea's house is bigger that _______.",
    "My father, who did not allow me to join the tour, has now given his _________.",
    "A _______ of robbers entered the city at night.",//120
    "He is a regular ________ at Reliance Mart.",
    "_________ should help the poor.",
    "When they entered their room, they saw a snake crawling on the _______.",
    "A _______ of arrows was fire at the deer by the hunter.",
    "I have bought three _______ notebooks.",
    "Spring has ______ own charm and delight.",
    "This table has benn made of______, taken from the nearby _______.",
    "His profession is teaching, although his ________ is photography.",
    "The dacoits looted their ________.",
    "It is _______ advice to use these ______ in a proper way.",
    "There was a _______ of ships in the harbour.",
    "Do you have any proof of ______ of this car?",
    "Here is the list of _______.",
    "We saw many horses at the ________.",
    "I had a very happy ________.",
    "In spite of a busy schedule and ______, she still managed to visit her friends.",
    "All the _______ went against him; hence he was guilty by the court.",
    "Mr. Jose is a man of _______.",
    "All the _____ in the house had been damaged during the flood last year.",
    "The firm was praised by the critics for its ________ in showing the horrors of war.",//140
    "The _______ of directors were perplexed.",
    "Many soft-hearted people can't see a horrible _______.",
    "The soldier was awarded a medal for his _______ in the war.",
    "He was hated for all his ________.",
    "A _______ of birds is always a beautiful sight",
    "A _______ of bees attacked Jack in the park.",
    "As you forgot to put your ________ on the cheque, I wasn't able to withdraw money.",
    "In any case, we are soon captivated by the beauty of the coastal ________.",
    "My teacher likes the literature of the sixteenth and seventeenth ________.",
    "Without _______, there is no happiness.",
    "Time once lost cannot be _________. ",
    "I have often _______- why she went to live abroad.",
    "After a lengthy discussion, they _______ a final decision.",
    "The best thing about childred is that they _________ very quickly to new environments.",
    "Fred, carry ________ my orders without arguments",
    "He was lonely and aching _______ love.",
    "Everyone wants to _____ stress.",
    "It is kind to ________ to speak at the end of the meeting.",
    "The sick woman _______ last night.",
    "Nobody will _________ this matter.",
    "She was _______ by her grandmother.",
    "They have really _______ the price of DVD players.",
    "I would like to _______ about my New Zealand Trip.",
    "The teacher ________ the students to copy the answer.",
    "he _________ the radio before going to bed.",
    "He generally _________ at an odd hour.",
    "A massive gold necklace ________ around her neck.",
    "You should _________ your study.",
    "The orator stopped for a while and then ________ speaking",
    "Why are you ________ a whisper.",
    "I ________ accuracy in your work.",
    "When you ______ a new car, you should start by reading consumer magazines",
    "There was a power failure, all the lights _________, but she had no candle.",
    "As the years passed, the memories ___________.",
    "You should ________ her proposal.",
    "The police are ________ the case currently.",
    "The present disturbances will soon _________.",
    "Mr Franl has ________ the business to his eldest son.",
    "The novelist and poet ________ dead.",
    "I _________ my hat when I came home.",//180
    "Nobody is ready to be _________ their freedom.",
    "Tomorrow's match has been _______ because of the icy weather.",
    "The teacher gives many example to __________ the idea contained in the poem.",
    "Either Dhoni and Virat __________ going to be the captain for the next one-day series.",
    "To furnish means __________.",
    "The heart keeps the blood _________ in the body.",
    "The passenger ______ the bus.",
    "Scott agreed to ___________ my orders.",
    "The teacher ordered Steve to leave the room and _________ him to return.",
    "_________ did the child weep?",
    "___________ he came to my village, he visited the famous temple in our district",
    "He often comes __________ to the class.",
    "He will be granted bail _______.",
    "The table was so light that I could __________ lift it.",
    "She looked at me _________ when I interrupted her.",
    "He lives ___________ despite having inherited his grandfather's property.",
    "I haven't finished my graduation ________.",
    "He often plays his FM too _________.",
    "__________ have you been reading here?",
    "I ________ not afford this costly bag. "















  };

  QString choices[200][4] = {
    {"Somewhere","Something","Someone","Somebody"},
    {"this","these","it","it's"},
    {"Everyone","Eachone","Each Of","Every"},
    {"who","how","what","whom"},
    {"my","yours","our","ours"},
    {"its","her","his","it's"},
    {"You, he and I","I, you and he","I, him and you","I, he and you"},
    {"this","he","the same","it"},
    {"whose","when","whom","who"},
    {"themselves","herself","himself","itself"},
    {"which","what","who","whose"},
    {"they","their","your","theirs"},
    {"All of","Every of","Both of","All from"},
    {"his","theirs","their","its"},
    {"each other","each another","each other","one another"},
    {"neither","all","each","either"},
    {"cheaper ones","cheaper once","cheaper one's","cheaper one"},
    {"his","them","him","he"},
    {"Who","Whom","Whose","How"},
    {"Loyalty","Loyalness","Royalty","Loyal"},//20
    {"years'","year's","years's","years"},
    {"stationery","stationary","stationnary","stationari"},
    {"appointments","advertisements","declarations","announcements"},
    {"son's","son","of son","son of"},
    {"appoinment","interview","meeting","billet"},
    {"My car's horn","My horn of car","My car-horn's","The horn of my car"},
    {"army","flock","team","colony"},
    {"essential thing","essential","essentials","essentials one"},
    {"plane's crashing","plane's crashing","plane crashing","plan's crashing"},
    {"widow","widower","spinster","bachelor"},
    {"inings","inning","innings","ining"},
    {"bird","bride","bribe","bridge"},
    {"The Prince of Waless'","The Prince of Wales","The Prince's of Wales'","The Prince of Wales'"},
    {"pack","herd","band","group"},
    {"offspring","springs off","offsprings","spring offs"},
    {"their","his","its","her"},
    {"servants","servant","servant's","servants'"},
    {"the feminine smile","the women's smile","the woman smile","the smile of a woman"},
    {"his","her","its","their"},
    {"connection","conservation","conversation","converse"},//40
    {"scenary","scenario","sceneries","scenerio"},
    {"Freedom","Freeship","Free","Freeness"},
    {"collection","series","stock","tuft"},
    {"womans-drivers","women-drivers","woman-drivers","women-driver"},
    {"Hiren's wife's parents","the parents of Hiren's wife","Hiren wife's parents","Hiren's wive's parents"},
    {"iron","iron's","irons","ironman"},
    {"a five star's hotel","a five start' hotel","five star hotel","a five-star hotel"},
    {"The prime minister's of india","The Prime's minister of India","The Prime Minister of India's","The prime minister of india"},
     {"swarm","flock","school","group"},
     {"group","gang","horde","herd"},
     {"solace","respite","warm","sympathy"},
     {"Geeses'","Gooses'","None","Geeses's"},
     {"thousands","thousand's","rupees","thousand"},
     {"decorate, antrance","decoration, entrance","d'cor, entertain","decorating, enter"},
     {"physic","physical","physics","physique"},
     {"The beauty of everything","Everything's Beauty","Everything's beauti","The beauty's everything"},
     {"its","their","his","her"},
    {"pick-me-up","up-me-pick","picks-up-me","pick-up-me"},
    {"amount","deal","number","numbers"},
    {"Alms'","Alms","Alm's","Alm"},
    {"Island","oaseses","oasises","oases"},
    {"confidence","confidant","confidunt","conffident"},
    {"foot, horse","feet, horse","foors, horses","feet, horses"},
    {"She","It","He","It's"},
    {"questions's","question's","question","questions"},
    {"group","commitee","jury","committee"},
    {"spinster","widower","bachelorette","widow"},
    {"year's ","years'","year","years"},
    {"Jack","Jacks","Jacks'","Jack's"},
    {"pack","troop","staff","herd"},
    {"pupils","counters","peoples","people"},
    {"youth","younger","youngster","youngman"},
    {"furnitures","farnitures","furniture's","furniture"},
    {"Vimal","Vimal's","Of vimal","Vimal of"},
    {"content","contentments","contents","contented"},
    {"comitee","commitee","committee","comitee"},
    {"India players","The Indian players","India's players","The Indians players"},
    {"warm","insurance","empathy","sympathy"},
    {"shadow","shade","shame","shades"},
    {"dancer","queen","princess","hostess"},
    {"herd","floor","fight","flock"},
     {"permission","obligation","allow","permitted"},
     {"gentry","army","jury","court"},
     {"widow","spinster","bride","bachelor"},
     {"bridegroom","spinster","widow","bride"},
     {"the ","he","it","she"},
     {"rapport","release","respite","pain free"},
     {"maid","woman","lady","laid"},
     {"voice","voise","noice","noise"},
    {"celebrating","celebration","celebrates","celebrate"},
    {"starship","starhood","stardom","Bollywood"},
    {"bride","bridegroom","bribe","bridge"},
    {"breads","bracelets","bracs","braces"},
    {"his","her","their","its"},
    {"my sister-friend's marriage","my sister's friend's marriage","my sister's friend marriage","the marriage of my sister's friend"},
    {"How horrible","How a horrible","what horrible","What a horrible"},
    {"spends-thrift","spendtthrift","extra vagant","spendthrift"},
    {"sympathy","warmth","reassurance","empathy"},
    {"herd","flock","swarm","group"},
    {"mob","gang","army","posse"},
    {"traitor","traitress","trail","trailor"},
    {"scenary","sceneries","scenerio","scenery"},
    {"Castillo","Castillos","Castillo's","Castillos'"},
    {"horses'","horse","horses","horse's"},
    {"facebook","air","heir","airs"},
    {"crowd","group","mob","temper"},
    {"scisor","sciccers","scissors","scissor"},
    {"infurmation","informations","informs","information"},
    {"week","wick","none","wise"},
    {"days","days'","day's","day"},
    {"pages after pages","pages after pages","page after page","pages after page"},
    {"a village, a village","villages, villages","village, village","village ,villages"},
    {"godliness","gogly","god","godlyness"},
    {"its","him","his","her"},
    {"poem","poet","poetries","poesy"},
    {"phenomena","phenomenons","phenomenal","phenomenon"},
    {"criseses","crisis","crisises","crises"},
    {"of Garcia","Garcia","Garcia of","Garcia's"},
    {"ascent","accent","assent","ascend"},
    {"group","pack","gang","mob"},//120
    {"client","costimer","costumer","customer"},
    {"Riches","The rich","Rich","The richess"},
    {"floor","ground","surface","flour"},
      {"multiple","range","flock","quiver"},
      {"dozen's","dozen","dozens","dozens'"},
      {"its","his","their","her"},
      {"wooden, woods","wood, woody","woods, wood","wood, woods"},
      {"vocational","vocation","avocation","vacation"},
      {"jewelry","jiwelleri","jewellery","jewelleries"},
      {"goods, good","good, goods","god, good","goods, good"},//130
      {"troop","flight","flotilla","flock"},
      {"owner sheep","ownership","ownersheep","owner ship"},
      {"stationary","stationery","stationeries","stationaries"},
      {"den","kenel","hutch","stable"},
      {"boydom","boyhood","boyship","boywood"},
      {"predilection","preoccupation","prediction","occupations"},
      {"evidances","evedence","evidences","evidence"},
      {"later","letter","letters","latter"},
      {"equipments","equips","equipment","eqiupmnet"},
      {"realship","real","realism","realhood"},//140
      {"committee","bored","group","board"},
      {"pair of spectacles","pairs of spectacles","spectacle","spectacles"},
      {"bravery","bravity","braveness","brabery"},
      {"selfless","selflessness","selfishness","selfish"},
    {"range","group","fleet","flight"},
    {"swarm","group","heap","school"},
    {"sign","signed","resign","signature"},
    {"sceneries","scenary","scenery","scenario"},
    {"centurys","centuri","centuriy's","centuries"},
    {"health","healthy","healthiness","healthify"},
    {"employed","gained","re-done","exchanged"},
    {"amazed","puzzled","wondered","engrossed"},
    {"arrived at","arrived in","arrived on","reached at"},
    {"adept","adopt","agree","adapt"},
    {"away","on","near","out"},
    {"about","in","with","for"},
    {"get into","get in","get out","get rid of"},
    {"comply","agree","concur","accept"},
    {"passed away","passed for","passed by","passed down"},
    {"agree to","agree on","agree in","agree with"},
    {"brought for"," brought in","brought out","brought up"},
    {"brought off","brought out","brought down","brought in"},
    {"say","describe","said","talk"},
    {"asked","tell","called","said"},
    {"turned out","turned away","turned up","turned off"},
    {"turns up","turns on","turns over","turns off"},
    {"hung","hanged","hanging","tied"},
    {"carry on","carry off","carry away","carry out"},
    {"went up","went on","went off","went away"},
    {"speaking to","speaking for","speaking into","speaking in"},
    {"none of the above","insist out","insist with","insist on"},
    {"purchase for","shop for","afford for","get for"},
    {"went on","went out","went away","went back"},
    {"went away","passed away","faded away","ran away"},
    {"agree on","agree with","agree to","agree by"},
    {"looking in","looking for","looking at","looking into"},
    {"blow out","blow into","blow in","blow over"},
    {"handed over","handed out","handed back","handed round"},
    {"have","is","was","are"},
    {"put out","put on","put off","put in"},//180
    {"deprived of","accused of","deprived from","get rid of"},
    {"called up","called back","called off","called out"},
    {"bring about","bring out","bring forth","bring in"},
    {"will","were","is","are"},
    {"support","appose","alter","provide"},
    {"circulating","running","flowing","moving"},
    {"alighed by","alighted into","alighted from","alighted to"},
    {"carry away","carry off","carry out","carry on"},
    {"stopped","forbade","challenged","refused"},
    {"Wherefore","Whom","Whence","Where of"},
    {"Whence","Somehow","However","Whenever"},
    {"late","latter","letter","lately"},
    {"short","quickly","fastly","shortly"},
    {"hardly","scarcely","easily","barely"},
    {"angry","angry away","angerly","angrily"},
    {"misery","miserly","miserily","like a miser"},
    {"never","still","ever","yet"},
    {"loud","high","highly","loudlyness"},
    {"How often","How far","How long","How old"},
    {"can","may","might","should"}












  };
  char answer[200]={
    'B','A','C','D','C','A','B','D','C','A',//10
    'A','D','C','C','D','A','A','D','A','A',
    'A','A','B','A','B','D','D','C','C','B',
    'C','B','D','A','A','B','A','D','C','C',
    'B','B','A','B','B','C','D','C','C','C',
    'A','D','D','B','D','A','B','A','A','B',
    'D','B','C','D','D','D','C','C','D','D',
    'C','A','D','B','C','C','B','C','C','A',
    'D','A','C','B','A','C','C','B','D','B',
    'C','A','D','D','D','D','D','D','A','D',
    'A','D','B','C','B','C','C','D','B','B',
    'C','C','A','A','D','A','D','D','C','C',
    'D','B','A','D','B','D','D','B','C','B',
    'C','B','B','D','B','B','D','C','C','C',
    'D','C','A','C','D','A','D','C','D','A',
    'B','C','A','D','D','D','D','B','A','B',
    'D','C','D','A','D','A','A','A','B','D',
    'D','B','B','C','C','D','D','A','D','C',
    'A','C','B','C','D','A','C','C','B','A',
    'D','A','D','C','D','D','D','A','C','A'




  };

  QString question_1[200] = {
    "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "Only one of the following words in correct, Which one?",
      "What is the Plural of the word \"Wife\"?",
      "What is the Plural of the word \"Kiss\"?",
      "What is the Plural of the word \"Child\"?",
      "What is the Plural of the word \"Sheep\"?",
      "What is the Plural of the word \"Diagnosis\"?",
      "What is the Plural of the word \"Tomato\"?",
      "What is the Plural of the word \"Clock\"?",
      "What is the Plural of the word \"Person\"?",
      "What is the Plural of the word \"Fish\"?",
      "What is the Plural of the word \"Shorts\"?",//20
    "What is the Plural of the word \"Calf\"?",
    "What is the Plural of the word \"Cuff\"?",
    "What is the Plural of the word \"Schema\"?",
    "What is the Plural of the word \"Criterion\"?",
    "What is the Plural of the word \"Lady\"?",
    "What is the Plural of the word \"Baby\"?",
    "What is the Plural of the word \"Larva\"?",
    "What is the Plural of the word \"Focus\"?",
    "What is the Plural of the word \"Cactus\"?",
    "What is the Plural of the word \"Ox\"?",//30
    "What is the Plural of the word \"Oasis\"?",
    "What is the Plural of the word \"Loaf\"?",
    "What is the Plural of the word \"Penny\"?",
    "What is the Plural of the word \"Kudos\"?",
    "What is the Plural of the word \"Species\"?",
    "What is the Plural of the word \"Deer\"?",
    "What is the Plural of the word \"Scissors\"?",
    "What is the Plural of the word \"River\"?",
    "What is the Plural of the word \"Syllabus\"?",
    "What is the Plural of the word \"Index\"?",
    "What is the Plural of the word \"Woman\"?",
    "What is the Plural of the word \"Premises\"?",
    "What is the Plural of the word \"Judge\"?",
    "What is the Plural of the word \"Sky\"?",
    "What is the Plural of the word \"Phenomenon\"?",
    "What is the Plural of the word \"Goose\"?",
    "What is the Plural of the word \"Cat\"?",
    "What is the Plural of the word \"Human\"?",
    "What is the Plural of the word \"Premises\"?",
    "What is the Plural of the word \"Analysis\"?",
    "What is the Plural of the word \"Phase\"?",
    "What is the Plural of the word \"Panties\"?",
    "What is the Plural of the word \"Radius\"?",
    "What is the Plural of the word \"Moose\"?",
    "What is the Plural of the word \"Crisis\"?",
    "What is the Plural of the word \"Photo\"?",
    "What is the Plural of the word \"Leaf\"?",
    "What is the Plural of the word \"Knife\"?",
    "What is the Plural of the word \"Aircraft\"?",
    "What is the Plural of the word \"Piano\"?",
    "What is the Plural of the word \"Box\"?",
    "What is the Plural of the word \"Half\"?",
    "What is the Plural of the word \"Life\"?",
    "What is the Plural of the word \"Datum\"?",
    "What is the Plural of the word \"Fungus\"?",
    "What is the Plural of the word \"Cherry\"?",
    "What is the Plural of the word \"Cello\"?",
    "What is the Plural of the word \"Bus\"?",
    "What is the Plural of the word \"Wish\"?",
    "What is the Plural of the word \"Dish\"?",
    "What is the Plural of the word \"Zero\"?",
    "What is the Plural of the word \"Feet\"?",
    "What is the Plural of the word \"City\"?",
    "What is the Plural of the word \"Potato\"?",
    "What is the Plural of the word \"Chair\"?",
    "What is the Plural of the word \"Mouse\"?",
    "What is the Plural of the word \"Spy\"?",
    "What is the Plural of the word \"Pitch\"?",
    "What is the Plural of the word \"Girl\"?",
    "What is the Plural of the word \"Man\"?",
    "What is the Plural of the word \"Goggles\"?",
    "What is the Plural of the word \"Trousers\"?",
    "What is the Plural of the word \"Massage\"?",
    "What is the Plural of the word \"House\"?",
    "What is the Plural of the word \"Stratum\"?",
    "What is the Plural of the word \"Appendix\"?",
    "What is the Plural of the word \"Tooth\"?",
    "What is the Plural of the word \"Memo\"?",
    "What is the Plural of the word \"Daisy\"?",
    "What is the Past Tense of the word \"Cut\"?",
    "What is the Past Tense of the word \"Hit\"?",
    "What is the Past Tense of the word \"Stand\"?",
    "What is the Past Tense of the word \"Bring\"?",
    "What is the Past Tense of the word \"Broadcast\"?",
    "What is the Past Tense of the word \"Hold\"?",
    "What is the Past Tense of the word \"Draw\"?",
    "What is the Past Tense of the word \"Run\"?",
    "What is the Past Tense of the word \"Make\"?",
    "What is the Past Tense of the word \"Boil\"?",
    "What is the Past Tense of the word \"Lead\"?",//
    "What is the Past Tense of the word \"Leave\"?",
    "What is the Past Tense of the word \"Show\"?",
    "What is the Past Tense of the word \"Lose\"?",
    "What is the Past Tense of the word \"Go\"?",
    "What is the Past Tense of the word \"Tell\"?",
    "What is the Past Tense of the word \"Drink\"?",
    "What is the Past Tense of the word \"Fall\"?",
    "What is the Past Tense of the word \"Flap\"?",
    "What is the Past Tense of the word \"Let\"?",
    "What is the Past Tense of the word \"Get\"?",//
    "What is the Past Tense of the word \"Understand\"?",
    "What is the Past Tense of the word \"Begin\"?",
    "What is the Past Tense of the word \"Catch\"?",
    "What is the Past Tense of the word \"Eat\"?",
    "What is the Past Tense of the word \"Wake\"?",
    "What is the Past Tense of the word \"Appreciate\"?",
    "What is the Past Tense of the word \"Win\"?",
    "What is the Past Tense of the word \"Grip\"?",
    "What is the Past Tense of the word \"Keep\"?",
    "What is the Past Tense of the word \"Grow\"?",//
    "What is the Past Tense of the word \"Have\"?",
    "What is the Past Tense of the word \"Give\"?",
    "What is the Past Tense of the word \"Hug\"?",
    "What is the Past Tense of the word \"Awake\"?",
    "What is the Past Tense of the word \"Carry\"?",
    "What is the Past Tense of the word \"Lie\"?",
    "What is the Past Tense of the word \"Lay\"?",
    "What is the Past Tense of the word \"Think\"?",
    "What is the Past Tense of the word \"Bat\"?",
    "What is the Past Tense of the word \"Drip\"?",
    "What is the Past Tense of the word \"Sleep\"?",
    "What is the Past Tense of the word \"Send\"?",
    "What is the Past Tense of the word \"Choose\"?",
    "What is the Past Tense of the word \"Build\"?",
    "What is the Past Tense of the word \"Say\"?",
    "What is the Past Tense of the word \"Forgive\"?",
    "What is the Past Tense of the word \"Lend\"?",
    "What is the Past Tense of the word \"Speak\"?",
    "What is the Past Tense of the word \"Bit\"?",
    "What is the Past Tense of the word \"Tear\"?",
    "What is the Past Tense of the word \"Hear\"?",
    "What is the Past Tense of the word \"Write\"?",
    "What is the Past Tense of the word \"Dig\"?",
    "What is the Past Tense of the word \"Hurt\"?",
    "What is the Past Tense of the word \"Wear\"?",
    "What is the Past Tense of the word \"Drag\"?",
    "What is the Past Tense of the word \"See\"?",
    "What is the Past Tense of the word \"Bend\"?",
    "What is the Past Tense of the word \"Spend\"?",
    "What is the Past Tense of the word \"Find\"?",
    "Which of the following is the Antonym of the word \"Private\"?",
    "Which of the following is the Antonym of the word \"Compassionate\"?",
    "Which of the following is the Antonym of the word \"Bad\"?",
    "Which of the following is the Antonym of the word \"Crazy\"?",
    "Which of the following is the Antonym of the word \"Audacious\"?",
    "Which of the following is the Antonym of the word \"Cool\"?",
    "Which of the following is the Antonym of the word \"Easy\"?",
    "Which of the following is the Antonym of the word \"Sturdy\"?",
    "Which of the following is the Antonym of the word \"Visible\"?",
    "Which of the following is the Antonym of the word \"Random\"?",
    "Which of the following is the Antonym of the word \"Arrogant\"?",
    "Which of the following is the Antonym of the word \"Never\"?",
    "Which of the following is the Antonym of the word \"Major\"?",
    "Which of the following is the Antonym of the word \"Capture\"?",
    "Which of the following is the Antonym of the word \"Wealth\"?",
    "Which of the following is the Antonym of the word \"Ascend\"?",
    "Which of the following is the Antonym of the word \"Right\"?",
    "Which of the following is the Antonym of the word \"Optimist\"?",
    "Which of the following is the Antonym of the word \"Worthy\"?",
    "Which of the following is the Antonym of the word \"Check\"?",//
    "Which of the following is the Antonym of the word \"Marvelous\"?",
    "Which of the following is the Antonym of the word \"Conventional\"?",
    "Which of the following is the Antonym of the word \"Triumph\"?",
    "Which of the following is the Antonym of the word \"Absent\"?",
    "Which of the following is the Antonym of the word \"Compulsory\"?",
    "Which of the following is the Antonym of the word \"Fat\"?",
    "Which of the following is the Antonym of the word \"Remember\"?",
    "Which of the following is the Antonym of the word \"Wet\"?",
    "Which of the following is the Antonym of the word \"Same\"?",
    "Which of the following is the Antonym of the word \"Full\"?",
    "Which of the following is the Antonym of the word \"Accumulate\"?",
    "Which of the following is the Antonym of the word \"True\"?",
    "Which of the following is the Antonym of the word \"Better\"?",
    "Which of the following is the Antonym of the word \"Vague\"?",
    "Which of the following is the Antonym of the word \"Well\"?",
    "Which of the following is the Antonym of the word \"Arrive\"?",
    "Which of the following is the Antonym of the word \"Regret\"?",
    "Which of the following is the Antonym of the word \"Segregate\"?",
    "Which of the following is the Antonym of the word \"Laugh\"?",
    "Which of the following is the Antonym of the word \"Old\"?",
    "Which of the following is the Antonym of the word \"Benevolence\"?",
    "Which of the following is the Antonym of the word \"Often\"?",
    "Which of the following is the Antonym of the word \"Stay\"?",
    "Which of the following is the Antonym of the word \"Giant\"?",
    "Which of the following is the Antonym of the word \"Argue\"?",
    "Which of the following is the Antonym of the word \"Deep\"?",
    "Which of the following is the Antonym of the word \"Finish\"?",
    "Which of the following is the Antonym of the word \"Transparent\"?",
    "Which of the following is the Antonym of the word \"Eager\"?",
    "Which of the following is the Antonym of the word \"Genuine\"?"



  };
  QString choices_1[200][4] = {
    {"Resette","Reseet","Reseat","Reset"},
     {"Subbject","Subject","Subgect","subgect"},
     {"Lurn","lyrn","learn","lern"},
     {"Bannana","Bannanaa","Bananna","Banana"},
     {"Busines","Business","Buisness","Bussiness"},
     {"Balloone","Baloon","Ballon","Balloon"},
     {"Password","Passwerd","Passwurd","Paswword"},
     {"Wrist","Rish","Wrisst","Wriste"},
     {"Truth","Truthe","Trooth","Truuuut"},
     {"Correctt","Coreect","Correct","Corecct"},//10
     {"Wiwes","Wifes","Wife","Wives"},
     {"Kiss","Kisses","Kisss","Kissess"},
     {"Children","Childs","Childes","Childrens"},
     {"Sheepes","Sheep","Sheap","Sheeps"},
     {"Diegnoses","Diagnosas","Diagnoses","Diagnosys"},
     {"Tometoes","Tomatoes","Tometos","Tomato"},
     {"Clockes","Clock","Clocks","Clockies"},
    {"Peoples","Persones","People","Persons"},
    {"Fishs","Fish","Fishies","Fishes"},
    {"Shortes","Shorts","Shorties","Shortis"},//20
    {"Calves","Calvs","Calwes","Calfs"},
    {"Cuff","Cuffes","Cuvs","Cuffs"},
    {"Scheme","Schemeta","Schemata","Schamata"},
    {"Criteria","Criteriones","Criterias","Critaria"},
    {"Ladyes","Lady","Lades","Ladies"},
    {"Babyies","Babies","Babyes","Babys"},
    {"Larvae","Larvas","Larvaes","Lervaes"},
    {"Foci","Focuss","Focuses","Focusses"},
    {"Cacti","Cactues","Cacties","Cactis"},
    {"Oxen","Oxan","Oxon","Oxel"},//30
    {"Oasas","Oases","Oasises","Oesis"},
    {"Loafes","Loavs","Loafs","Loaves"},
    {"Pennyies","Pennies","Pennyes","Pennys"},
    {"Kudes","Kudoses","Kudas","Kudos"},
    {"Species","Speces","Spices","Spacies"},
    {"Deeres","Deers","Dear","Deer"},
    {"Scissars","Scissores","Scissers","Scissors"},
    {"River","Rivars","Rivers","Riveres"},
    {"Syllebi","Syllabies","Syllabes","Syllabi"},
    {"Indices","Indexes","Indises","Indexs"},//40
    {"Womans","Woman","Women","Womens"},
    {"Pramises","Premisas","Premises","Premiseses"},
    {"Judge","Judgges","Judgees","Judges"},
    {"Skis","Skyes","Skyies","Skies"},
    {"Phenomenons","Phanomena","Phenomena","Phenomenon"},
    {"Geese","Goese","Giisi","Gooso"},
    {"Cats","Caties","Cat","Cates"},
    {"Humens","Humanss","Humans","Humanses"},
    {"Pramises","Premises","Premisas","Premiseses"},
    {"Analysis","Analyses","Analysises","Anelyses"},//50
    {"Phases","Pheses","Phasis","Phasees"},
    {"Pantiies","Penties","Pantis","Panties"},
    {"Radies","Radee","Radii","Radius"},
    {"Mooses","Muse","Moose","Meese"},
    {"Crises","Crisises","Criseses","Crisys"},
    {"Photos","Photo","Photoes","Photoss"},
    {"Leaves","Leavs","Leafes","Laeves"},
    {"Knives","Knieves","Knifes","Kniefeses"},
    {"Aircrafties","Aircrafts","Aircraft","Aircraftes"},
    {"Pianos","Pienos","Piano","Pianoes"},//60
    {"Boxess","Boxes","Box","Boxsis"},
    {"Halfes","Halfs","Halves","Halfses"},
    {"Lifes","Lives","Lifses","Life"},
    {"Datumes","Datas","Datums","Data"},
    {"Fungi","Fungies","Fungis","Fungises"},
    {"Cherry","Charries","Cherres","Cherries"},
    {"Celloes","Celloss","Cellos","Celloos"},
    {"Bus","Buss","Busies","Buses"},
    {"Wishes","Wishies","Wish","Wishs"},
    {"Dish","Dishs","Dishes","Deshes"},//70
    {"Zeroes","Zero","Zeros","Zeroses"},
    {"Feet","Feets","Footes","Foots"},
    {"Cityes","Citys","Cityies","Cities"},
    {"Potatoes","Potatoos","Potatoes","Potato"},
    {"Chaires","Chairs","Chair","Chairses"},
    {"Micies","Mouses","Mices","Mice"},
    {"Spys","Spies","Spyes","Spyies"},
    {"Pitchs","Pitcheses","Pitches","Petches"},
    {"Girl","Girles","Girls","Girlses"},
    {"Mans","Man","Men","Mens"},//80
    {"Goggles","Goggales","Googles","Goglass"},
    {"Trousors","Trousars","Trouseres","Trousers"},
    {"Massage","Messages","Massages","Massagges"},
    {"Hoeses","Houses","Housees","House"},
    {"Startumes","Startes","Strati","Stretums"},
    {"Appendiceses","Appendices","Appendise","Appendece"},
    {"Teeth","Teeths","Tooths","Toothes"},
    {"Memoes","Memoses","Memos","Mamos"},
    {"Daisys","Daisyes","Daisies","Daisyies"},
    {"Cutted","Cuted","Cot","Cut"},//90
    {"Hitted","Hot","Hit","Hat"},
    {"Standed","Stood","Stend","Standed"},
    {"Bring","Brought out","Bringed","Brought"},
    {"Braodcast","Broadcastted","Broadcost","Broadcast"},
    {"Holded","Hold","Held","Helded"},
    {"Draw","Drawed","Drewed","Drew"},
    {"Ran","Ron","Run","Ren"},
    {"Made","Meda","Maked","Moke"},
    {"Boileded","Boilad","Boiled","Boilled"},
     {"Leaded","Lead","Load","Led"},//100
     {"Leave","Left","Leaved","Gone"},
     {"Showed","Shew","Showwed","Shawed"},
     {"Losed","Lose","Lost","Loss"},
     {"Go","Gone","Went","Wented"},
     {"Told","Tald","Telled","Teld"},
     {"Drenk","Drunk","Drink","Drank"},
     {"Fall","Felled","Falled","Fell"},
     {"Fleppad","Flapped","Flaped","Flepped"},
     {"Letted","Leted","Let","Lated"},
     {"Got","getted","Get","Geted"},//110
     {"Understoud","Understuod","Understanded","Understood"},
     {"Beginning","Began","Begin","Begin"},
     {"Caught","Catched","Catch","Cought"},
     {"Ate","Eat","Eated","Eatted"},
     {"Wakked","Waked","Woka","Woke"},
     {"Appraciated","Appreceated","Appreciated","Apprecieted"},
     {"Wonned","Wined","Wan","Won"},
     {"Grip","Grippad","Gripped","Griped"},
    {"Kept","Kopt","Kapt","keeped"},
    {"Grew","Growed","Greow","Growened"},//120
    {"Hed","Had","Has","Haved"},
    {"Gived","Gabed","Gave","Gove"},
    {"Huged","Hug","Hugged","Huggad"},
    {"Awaked","Awoke","Awake","Aweke"},
    {"Cerried","Carried","Carryed","Carriad"},
    {"Lied","Ley","Layed","Lay"},
    {"Layed","Leid","Layyed","Laid"},
    {"Thaught","Think","Thinked","Thought"},
    {"Batted","Bot","Bated","Bat"},
    {"Drippad","Drippod","Driped","Dripped"},//130
    {"Sleepped","Slopt","Slept","Sleeped"},
    {"Sended","Send","Sand","Sent"},
    {"Choossed","Chosed","Choosed","Chose"},
    {"Builded","Built","Build","Bouild"},
    {"Seid","Said","Saided","Sayed"},
    {"Forgived","Forgaved","Forgave","Forgive"},
    {"Lended","Lent","Land","Lant"},
    {"Speka","Speaked","Speak","Spoke"},
    {"Bitted","Bite","Bit","Bited"},
    {"Taer","Torr","Tore","Taro"},//140
    {"Haerd","Hearred","Heard","Heared"},
    {"Write","Wrote","Writted","Wrate"},
    {"Dug","Dugged","Digged","Diged"},
    {"Hurt","Hurtted","Hurted","Hort"},
    {"Woar","Wore","Weared","Wored"},
    {"Dregged","Draged","Drag","Dragged"},
    {"Sow","Seed","Sew","Saw"},
    {"Bent","Bond","Bend","Bant"},
    {"Spent","Spanded","Spended","Spendded"},
    {"Found","Fond","Finded","Find"},
    {"Personal","Individual","Parricular","Public"},
     {"Caring","Understanding","Sympathetic","Indifferent"},
     {"Good","Cheap","Rough","Awful"},
     {"Psycho","Insane","Nutty","Sane"},
     {"Resolute","Courageous","Careful","Adventurous"},
     {"Warm","Refrigerated","Refreshing","Chill"},
    {"Simple","Smooth","Difficult","Accessible"},
     {"Durable","Delicate","Well Built","Tough"},
     {"Noticeable","Observable","Easily Seen","Invisible"},
     {"Odd","Unexpected","Specific","Unusual"},//
     {"Egotistic","Bossy","Aloof","Humble"},
     {"No Way","Always","Not Ever","At No Time"},
    {"Considerable","Minor","Primary","Large"},
     {"Occupy","Take","Catch","Release"},
     {"Poverty","Luxury","Affluence","Prosperity"},
     {"Move up","Rise","Descend","Resend"},
     {"Good","Honest","Wrong","Proper"},
     {"Worshipper","Pessimist","Believer","Devotee"},
    {"Virtuous","Noble","Deserving","Worthless"},
     {"Inspect","Examine","Liberation","Scan"},//
     {"Extraordinary","Awesome","Terrible","Fabulous"},
     {"Ordinary","Regular","Typical","Extraordinary"},
     {"Defeat","Victory","Success","Achievement"},
     {"Present","Missing","Away","Gone"},
    {"Optional","Mandatory","Obligatory","Required"},
     {"Bulky","Big","Skinny","Heavy"},
     {"Recall","Recognize","Remind","Forget"},
     {"Aqueous","Liquid","Juicy","Dry"},
     {"Different","Equivalent","Equal","Identical"},
     {"Entire","Complete","Empty","Sufficient"},
    {"Seperate","Gather","Concentrate","Increase"},
     {"Accurate","!True","False","True"},
     {"Superior","Improved","Preferred","Worse"},
     {"Hazy","Unsure","Definite","Unclear"},
     {"Sick","Healthy","All Right","Vigorous"},
     {"Enter","Attain","Depart","Land"},
    {"Rejoice","Sorrow","Guilt","Sorry"},
     {"Separate","Sort Out","Integrate","Set Apart"},
     {"Smile","Happy","Chuckle","Cry"},
     {"Mature","Young","Ancient","Aged"},
     {"Goodness","Compassion","Spite","Kindness"},
     {"Usually","Regularly","Seldom","Generally"},
    {"Remain","Continue","Rest","Leave"},
     {"Jumbo","Monstrous","Dwwarf","Gigantic"},
     {"Quarrel","Dispute","Disagree","Agree"},
     {"Far","Shallo","Rooted","Low"},
     {"Close","Accomplishment","Finale","Beginning"},
     {"Clear","Opaque","See-Through","Translacent"},
    {"Interested","Uninterested","Curious","Hopeful"},
     {"Original","Fake","Real","Authentic"},








  };

  char answer_1[200] = {
    'D','B','C','D','B','D','A','A','A','C',
    'D','B','A','B','C','D','C','C','B','B',
    'A','D','C','A','D','B','A','A','A','A',
    'B','D','B','D','A','D','D','C','D','A',
    'C','C','D','D','C','A','A','C','B','B',
    'A','D','C','C','A','A','A','A','C','C',
    'B','C','B','D','A','D','C','D','A','C',
    'C','A','D','A','B','D','B','C','C','C',
    'A','D','C','B','C','B','A','C','C','D',
    'C','B','D','D','C','D','A','A','C','D',
    'B','A','B','C','A','D','D','B','C','A',
    'D','B','A','A','D','C','D','C','A','A',
    'B','C','C','B','B','D','D','D','A','D',
    'C','D','D','B','B','C','B','D','C','C',
    'C','B','A','A','B','D','D','A','A','A',
    'D','D','A','D','C','A','C','B','D','C',
    'D','B','B','D','A','C','C','B','D','C',
    'C','D','A','A','A','C','D','D','A','C',
    'A','C','D','C','A','C','A','C','D','B',
    'C','C','D','C','D','B','D','B','B','B'



  };









};

#endif // GRAMMARQUIZ_H
