#ifndef QUESTIONSTRUEORFALSEANDTRIVIA_H
#define QUESTIONSTRUEORFALSEANDTRIVIA_H
#include <QString>

class QuestionsTrueOrFalseAndTrivia
{
public:
  QuestionsTrueOrFalseAndTrivia();






private:
  QString trueOrFalseQuestions[200] = {

    "The capital of Michigan is Lansing. ",
    "The movie \"The Runaway Bride\" and \"Pretty Woman\" both star at least three of the same actors/actresses.",
    "The movie \"American Beauty\" won the Oscar for Best Picture.",
    "The birthstone for September is the sapphire.",
    "The following books are in the Old Testament of the Bible: Genesis, Exodus, Numbers and Leviticus.",
    "George Burns, the actor, lived to be 100 years old.",
    "The word \"right\" has 5 letters in it. ",
    "There are more than 100 quizzes on FunTrivia site. ",
    "The word \"Amore\" in Italian means \"Love\" in English.",
    "Toronto is the capital of Canada.",

    "Sylvester Stallone has been nominated for both an Academy Award for 'Best Actor' and a Razzie Award for 'Worst Actor' for playing the same role.",
    "'Call Me Ishmael' is the first line of the book 'Tom Sawyer'.",
    "In the US version of the game 'Monopoly', the color of Vermont Avenue is dark blue.",
    "In tennis, The Australian Open is one of the four tournaments making up the Grand Slam.",
    "Before becoming Governor of Texas, George W. Bush was co-owner of a professional baseball team.",
    "An elephant can smell water up to 3 miles away.",
    "The TV Show 'All in the Family' is based on a British TV Show.",
    "The doctor who tended to John Wilkes Booth after he shot Abraham Lincoln's name was Mudd.",
    "Dennis the Menace's favorite beverage is water.",
    "The Lone Ranger's horse was named Silver.",

    "The Lone Ranger's real name was John Reid before becoming The Lone Ranger.",
    "Tonto's horse was called Scout.",
    "Leo is the name of the MGM lion.",
    "Lennie and George were the main characters in Steinbeck's 'Of Mice and Men'",
    "Captain Kirk slept on Deck 5 in the T.V. series 'Star Trek'. ",
    "President F. D. Roosevelt declared December 7, 1941 'a date which will live in infamy'.",
    "Chester, on 'Gunsmoke' had the last name of Proudfoot. (radio version) ",
    "Paladin carried a Colt .45.",
    "Zip stands for Zone Improvement Plan.",
    "Lindsay Wagner played 'The Bionic Woman' in the T.V. series.",

    "Billy the Kid's real name was William H. Bologna.",
    "Billy Joe McAllister jumped off the Tallahatchie bridge.",
    "Over 1,000 Americans died at the Alamo.",
    "Alfred was Bruce Wayne's butler on the T.V. series 'Batman'.",
    "Pancho's horse was Lobo. Remember, he was The Cisco Kid's partner.",
    "Judy Jetson went to Orbit High School. ",
    "Tellus was the first U.S. communications satellite.",
    "Socrates taught Plato.",
    "Trieste Boy was Roy Roger's horse.",
    "When Pete Rose played for the Cincinnati Reds his number was 0.",

    "If you mix Jack Daniels and Jim Beam together you are making a gin and tonic.",
    "George Washington is noted for having almost perfect teeth.",
    "Robert E. Lee commanded the Army of the Potomac during the Civil War.",
    "George Jefferson was the President of the Confederate States during the Civil War.",
    "John Ritter was the father of Tex Ritter.",
    "The dog, Rin Tin Tin was actually a female dog.",
    "The Righteous Brothers' real names were Hatfield and McCoy.",
    "When the Jolly Green Giant first appeared on commercials he was actually the Jolly Yellow Giant.",
    "The Galloping Spook was Red Grange's nickname when he played football.",
    "The Super Mex is the nickname of pro-golfer Lee Trevino.",

    "'The Texas' chased 'The General' in the Great Locomotive Chase in the Civil War.",
    "The 'Texas Theatre' was the Dallas movie house where Lee Harvey Oswald was captured after the shooting of J.F.K.",
    "'The Buck Stops Here' was the saying on the sign on President Truman's desk.",
    "Terrytown was where Mighty Mouse lived.",
    "Fisher was the man's last name who appeared on the first U.S. postage stamp.",
    "Fred was the man's last name that coined the phrase, 'Rock and Roll'.",
    "Freeport was Mr. Wilson's pet dog on 'Dennis the Menace'.",
    "Fritzie was the name of William S. Hart's horse.",
    "Fryer was the name given to the Wright Brother's airplane.",
    "It is impossible to get a McDonald's Happy Meal in New Delhi, India.",

    "Women athletes competed with male athletes in the Ancient Greek Olympic Games.",
    "The first warship sunk by a submarine was during the American Civil War, when the Confederate sub 'Hunley' sunk the USS 'Housatonic'.",
    "King Akhenaten of Egypt was considered even more beautiful than his wife, Queen Nefertiti.",
    "The first Triceratops bones were discovered in 1889.",
    "Chocolate syrup was used to simulate blood in the old 1931 vampire classic 'Dracula' by Universal starring Bela Lugosi.",
    "Two days before Anthony Porter was to be executed for a double murder, he was granted a stay when students re-enacting the case discovered the real killer",
    "In 1775, Davey Crockett blazed the Wilderness Trail travelled by pioneers across the Appalachians of North Carolina through the Kentucky mountains. ",
    "If you are allergic to live animals, don't worry. You can adopt a mummy animal from Egypt's Cairo Museum.",
    "Adults have more bones than babies do. ",
    "In 1837, a law was passed by the United States Congress that every seagoing ship must carry a life preserver for every passenger.",

    "The biggest known volcano in the solar system is on Mars.",
    "Wilbur Wright died in 1908 of injuries he suffered when the protoype airplane, that he and his brother Orville had developed for the United States Army, crashed near Ft. Meyers, Virginia.",
    "The macaroni penguin of Antarctica gets its name from the old American Revolutionary war song 'Yankee Doodle'. ",
    "During the American Civil War, one of Confederate Gen. Kirby's Smith's officers received a coded message so complex, he had to ride around Union lines to ask the sender what in the heck he was saying.",
    "Found among Robert Louis Stevenson's effects after his death, was the original manuscript of 'Treasure Island' (rejected by his publisher) in which Stevenson reveals that Jim Hawkins's real father was Long John Silver.",
    "On July 20, 1969, American astronaut Alan Shepherd made the first footsteps ever on the surface of the moon.",
    "Florence Nightingale was known as the 'angel of mercy' for her ministrations to Union soldiers in the American Civil War, and for her tremendous efforts in founding the American Red Cross. ",
    "If you sneeze when suddenly exposed to intensely bright light, you have photosynthesis.",
    "The oldest rock on Earth was found by geologists in the outback of Australia in January, 2001.",
    "Strawberries have more Vitamin C than oranges.",
    "Niagara Falls is the highest waterfall in the world.",
    "Bowling was first played in Italy.",
    "The Los Angeles Zoo has the largest collection of animals.",
    "Harvard is the oldest college in the United States.",
    "On average, the 'eye muscles' move 300,000 times a day.",
    "The bulletproof vest was created by a woman.",
    "The leopard is the fastest mammal on earth.",
    "Cows have four-chambered stomachs. ",
    "No cast member on 'M*A*S*H*' served in the Korean War.",
    "The first sequel to win Best Picture at the Academy Awards was 'The Godfather Part II'.",
    "The only man-made structures that can be seen from outer space are the Great Pyramids.",
    "The United Nations was originally headquartered in San Francisco.",
    "Shanghai was once the largest city in the Communist world.",
    "Canada is the second largest country in terms of size/area.",
    "A cygnet is a baby dolphin.",
    "The official ball for the WNBA (Women's National Basketball Association) is red, white, and blue.",
    "NATO is an acronym for 'North American Treaty Organization'.",
    "Phylicia Rashad (Mrs. Huxtable on 'The Cosby Show') was once married to a member of the Village People.",
    "In 2000, The Mets and Cubs opened the Major League baseball season in Japan. This marked the first time that the baseball season has opened in a country other then the United States or Canada.",
    "A rat can last longer without water than a camel. ",
    "The '57' on the Heinz ketchup bottle represents the number of varieties of tomato the company once used.",
    "Before the book 'Peter Pan', the name Wendy had never been used.",
    "Charlie Chaplin once won third prize in a Charlie Chaplin look alike contest.",
    "In 'Gulliver's Travels', Jonathan Swift described the two moons of Mars, Phobos and Deimos, giving their exact size and speeds of rotation.",
    "Celery has so many calories that eating it isn't even a workout.",
    "Bruce Lee was so slow while going through his moves that they had to speed up one of his movies to make it look real.",
    "It took Leonardo da Vinci ten days to paint Mona Lisa's lips.",
    "During World War II, the Oscars were made of plaster.",
    "There are no known English words that rhyme with orange and purple.",
    "\"Dances With Wolves\" was released closer in time to the first moon landing than to the resignation of Pope Benedict XVI. ",
    "If you could fold a piece of paper in half 42 times it would be tall enough to reach the moon.",
    "While in space astronauts are slightly shorter than when they're on earth.",
    "The human residents of one of the Canary Islands communicate by whistling.",
    "Eating a Poinsettia will kill you (or your pet).",
    "Adults can't breathe and swallow at the same time.",
    "Smoking can make your nipples fall off.",
    "If you drop a penny from the Empire State Building, it will kill anyone it hits on landing",
    "To get a wart from a toad, you would have to touch the toad for five minutes or more.",
    "Dogs don't see in shades of grey, but can detect some colors. ",
    "Russia is larger in area than the minor planet, Pluto. ",
    " Lemmings commit mass suicide when they migrate by plunging off cliffs and drowning in the ocean.",
    "An octopus has three hearts.",
    "McDonald's marketed a product called the \"McLobster\".",
    "Swallowed chewing gum takes seven years to digest.",
    "Earth is closest to the sun in January.",
    "Abraham Lincoln's mother died from drinking the milk of a cow that grazed on poisonous snakeroot.",
    "A con man once sold the Eiffel Tower.",
    "There are about the same number of synapses (nerve connections) in your brain as there are stars in our galaxy.",
    "Mark Twain invented and patented the bra strap clasp.",
    "The loudest sound produced by any animal is 188 decibels trumpeted by the African Elephant. ",
    "Narwhals use their tusks to communicate with one another.",
    "Harvard University was founded before calculus was discovered.",
    "Silly mid on is a fielding position in cricket.",
    "There are only three words in the English language which end in \"dous\": tremendous, horrendous, and stupendous.",
    "The can-opener was not invented until more than 45 years after the invention of the tin can.",
    "90% of human DNA is identical to that of a banana.",
    "The Bahamas once had an undersea post office.",
    "Ronald Reagan was the first choice to play the role of Rick Blaine in \"Casablanca\".",
    "Alaska is obviously the furthest North of the United States. But it is also the furthest East and the furthest West."
   "Cats are mainly nocturnal/crepuscular.",
   "Cats see only in black and white.",
   "Cats are carnivores.",
   "Cats have whiskers on the backs of their front legs.",
    "Cats have a better sense of smell than humans.",
    "Cats with ringworm are infected with worms that form circular shapes underneath the surface of the skin.",
    "It's normal for cats to regularly breathe through their mouths.",
    "Cats have incredibly acute hearing.",
    "Chocolate can be toxic to cats.",
    "Cats use their whiskers to detect whether they'll be able to pass through an opening or not.",
    "Picking cats up by the scruff and carrying them long distances is always the best method of restraining them. ",
    "Aspirin can be deadly for cats.",
    "Short tails on cats are known as stud tails.",
    "Cats can develop feline acne.",
    "The feline AIDS virus is the same virus that causes AIDS in people.",
    "\"Alexander the Great\" was once the King of Macedonia.",
    "Diagonals drawn from opposing corners of a rectangle will always bisect each other.",
    "Harper Lee won the Pulitzer Prize for the novel \"To Kill A Mockingbird.\"",
    "Only the Chinese Tiger is an endangered tiger species.",
    "There are two main types of balls in the sport of Lawn Bowls: the \"bowl\" and the \"jack\".",
    "Michael Franti used to be the main singer in the band \"The Disposable Heroes of Hiphoprisy\"",
    "",
    "",
    "",
    "",
    "",
    "",
    "",





  };

  QString TrueOrFalseExplanation[200] = {

    "There are numerous cities in Michigan, including Holland where we celebrate the Tulip Time Festival every year. There is also the city of Detroit. \"Go, Go, Go Detroit Lions!\"",
    "Yes, both of these movies star the handsome Richard Gere, the beautiful Julia Roberts and the entertaining Hector Elizondo. Hector has been in numerous movies, including his dance scene with Julie Andrews in \"The Princess Diaries\".",
    "I don't get it. \"American Beauty\" wins Best Picture, beating out \"The Green Mile\" and \"The Sixth Sense\". Don't misunderstand me. I like Kevin Spacey. I adored Annette in \"The American President\", but \"American Beauty\"? Am I clueless here?",
    "Yes, the beautiful blue sapphire is the gem for the month of September. Actually September is a pretty cool month. In the United States, we celebrate the holiday, Labor Day, in September. The kids also go back to school around this time. We also get to welcome the season Fall in too.",
    "Genesis would be the first book in the Old Testament. Matthew is the first book in the New Testament. Matthew is followed by Mark, Luke and John too. Now, the last book of the Bible would be Revelation. Do you remember the song, \"The B I B L E... yes, that's the book for me, I stand alone on the word of God, the B I B L E."
    "George Burns was born in the bright city lights of New York, New York in 1896, in January. George and his wife, Gracie entertained audiences for many years. George passed away and left us in March of 1996 in Beverly Hills, California. From coast to coast, you left your mark, George. Thanks!",
    "You are right about this. Not to be confused with writing a letter though. You could say that she was right or wrong too. Maybe I'll just turn right to the next question here. Right?",
    "Yes, there's literally thousands of quizzes on this site. The quizzes are actually played by thousands of players too. We even have thousands of authors too. But, we only have a handful of editors. Remember, treat those editors with lots of kindness. They volunteer their time just for you!",
    "If you ever have seen the movie \"Moonstruck\" with Cher, this word is used quite often. \"Amore\" is in the air. \"Amore\" is in the moon. \"Amore\" is all around. Cher won the Oscar for Best Actress for this movie.",
    "Ottawa is the Capital of Canada. Toronto is the Capital of Ontario.",

    "Yes, he was nominated for 'Best Actor' in Rocky and 'Worst Actor' for Rocky V, playing the same role of Rocky Balboa.",
    "It's the first line to the book 'Moby Dick'.",
    "Its color is light blue. Boardwalk and Park Place are dark blue.",
    "The Australian Open, The French Open, Wimbledon, and The US Open comprise the Grand Slam in tennis.",
    "He was a co-owner of the Texas Rangers.",
    "Elephants have a keen sense of smell, detecting water sources up to 19.2 km (12 mi.) away. Nostrils are located at the tip of the trunk and function in breathing, smelling, and drawing water in to squirt into the mouth. ... Turbinals are curls of bone that have millions of olfactory receptor cells associated with them.",
    "It is based on the TV Show 'Til Death Us Do Part.'",
    "His name was Mudd",
    "His favorite is root beer.",
    "Debut WXYZ on Detroit radio January 30, 1933.",

    "Created by Fran Striker and George W. Trendle.",
    "Tonto actually gave The Lone Ranger his famous name.",
    "He first roared on July 31, 1928.",
    "They were Lennie Small and George Milton.",
    "So did Mr. Spock, Dr. McCoy and Mr. Scott.",
    "Pearl Harbor.",
    "Played by Parley Baer.",
    "From 'Have Gun Will Travel'.",
    "Introduced in 1962. So how well did you do? I sure hope you got 10/10 as I gave away still another clue as to how this quiz should be answered. Thanks for taking my quiz. Kabel :)",
    "She was injured in a skydiving accident and they made her bionic.",

    "William H. Bonney was his real name.",
    "\"Ode To Billy Joe\" by Bobbie Gentry.",
    "By all the accounts I have managed to look up it was more like 188 men that died fighting the Mexicans.",
    "Played by Alan Napier.",
    "Nope, it was Loco.",
    "Yup, she did. ",
    "No it was Telstar1 and it became active on 7-10-1962.",
    "Yup, and then Plato taught Aristotle.",
    "Nope, it was Trigger. Did you figure out the pattern? If you did then you got 10/10 and bettered your scoring. Hey, if you like my goofy way of doing T or F quizzes, drop me a line. Thanks Kabel :)",
    "Pete's number was 14. ",

    "Actually I think you are making a good hangover. ",
    "Actually he had an awful lot of problems with his teeth. There is a painting of him in the Cincinnati Art Museum sporting his famous wooden teeth.",
    "He commanded the Army of Northern Virgina. ",
    "It was Jefferson Davis.",
    "It's the other way around.",
    "No he was a male dog and his actual name was Rinty. Rinty was born in a trench in France during WW1.",
    "Bobby Hatfield and Bill Medley were their real names.",
    "He was always green.",
    "Red's nickname was the Galloping Ghost. I told you that all of the answers were false. Now I must be off. ",
    "That guy is not only good, he is funny to watch.",

    "It occured on April 12, 1862.",
    "November 22, 1963.",
    "President Carter also used that sign.",
    "From his cartoon series.",
    "Franklin was his name. Benjamin Franklin to be exact.",
    "Freed was his name. Alan Freed to be exact.",
    "Nope, it was Fremont.",
    "No, it was Fritz and he lived to be 31 years old.",
    "Flyer would have been the correct answer. Did you notice the 'clue' given in each statement? The first five questions all started with a 'T' and the last five with an 'F'. Oh what will Kabel come up with next!?",
    "Cows are sacred in much of India. Cow dung is burned for fuel and used for fertilizer. Cow's milk can be drunk. You can get a McDonald's Happy Meal, but the burger is going to be a 'lamb-burger'.",

    "Married women were not allowed to compete or attend the Ancient Greek Olympic Games. Since most girls were married at about 13 years old, very few spectators were female. But there were games for women athletes held in Olympia and throughout Greece. The Heraea Games, named after the god Zeus' wife Hera, featured foot races along a 525-foot track. Since men competed in the nude (remember all those Grecian statues and vases) there wasn't a chance of a lady in disguise slipping in the events at the Ancient Olympic Games.",
    "On Feb.17, 1864, the Confederate sub 'Hunley' rammed 90 pounds of gunpowder into the Union Navy ship 'Housatonic'. Within five minutes, the ship and its 155 member crew went to the bottom. The victory really seems a hollow one, doesn't it, as the 'Hunley' also was sunk.",
    "Actually, images of Akhenaten found in the early 1880s in his tomb at el-Amarna show the Pharaoh had a large head, narrow chin, and a thin neck. While this might not sound too unattractive, he is often depicted as having large breasts, big hips, and thin arms and legs, which some experts think was caused by a genetic disease. Akhenaten started his reign as Amenhotep IV, but changed his name in the fifth year he was king. The name Akhenaten means 'Aten is on the horizon', Aten being the sun. ",
    "Yes, and quite a find it was, too, for one of America's most respected paleontologists, Othniel Charles Marsh. Marsh was a professor at Yale University, and head of Yale's Peabody Museum. The find was made in Wyoming at Como Bluff. He may be as well remembered for his rivalry with another fossil hunter, Edward Drinker Cope, as he is for his fabulous finds. Before the two became enemies in their 'Bone Wars', they invented the 'plaster jacket' still used today by paleontologists to transport their finds from the digs.",
    "Nope. There wasn't actually any blood shown in the 1931 classic. The scares came from Lugosi's wonderful campy Count, a fine supporting cast, and its eerie stage-like atmosphere. Can you believe Lon Chaney was the first choice to play Drac?? Well, in Hitchcock's classic 'Psycho', the blood flowing down the drain during the famous shower scene was chocolate. Did you know it wasn't until Hammer started making their 'Dracula' offerings that the Count was ever filmed in 'living' color--sorry, terrible pun! I found this out in the DK version of the book 'Dracula'.",
    "Yes. Porter had been on death row two years for killing a young couple. After David Protess, a professor of journalism at Northwestern University, and his students re-enacted the crime, Alstory Simon confessed and Porter was set free.",
    "Nope. Sorry, it was Daniel Boone with 30 of his hardy woodsmen that blazed the Trail. By 1800, 200,000 pioneers had travelled the Wilderness Trail going west. Davey Crockett was certainly famous enough in his own right. Remember the Alamo?",
    "Well, you can't take a priceless animal mummy home, but for a donation you can 'adopt' one. The Museum will send you a photo, adoption certificate, and a story about your pet mummy. The money goes to the restoration of the Museum's animal mummies, which is a Good Thing, right? The mummies include crocodiles, ibises, cats, snakes, and dogs. Now you will be the first in your neighborhood to have your own pet mummy. ",
    "When we are born, we have over 300 bones. By the time we reach age 20, some of them have grown together making our skeletons stronger. As adults, we have about 206 bones.",
    "Yes, after 90 people lost their lives when the steamship 'Home' sank off the coast of Ocracoke Island, North Carolina during a hurricane in 1837, the US Congress passed a law that all seagoing ships must carry a life preserver for every passenger.",

    "Olympus Mons, on Mars, is the tallest and widest known volcano. The peak is nearly three times taller than Mt. Everest's. It is entirely out of Mars's atmosphere, and the base is about the size of Missouri. This is a very big volcano!",
    "Orville Wright did crash a plane he was testing for the US Army in 1908 near Ft. Myers, and the Army officer on board, as a passenger, was killed. Wilbur Wright died on May 29, 1912 of typhoid fever when he was 45. Orville died on Jan. 30, 1948.",
    "Remember the old song's words 'stuck a feather in his cap and called it macaroni'? The macaroni penguin has orange feathers on its head, so its name comes from this line of the song.",
    "Yes, indeed! After poring 12 long hours over the cypher, Major Cunningham hopped his horse, rode completely around Union lines and asked the sender 'What does this say?' The Major probably had a few choice words to say that history doesn't record, I bet.",
    "I just made this up off the top of my head. To my knowledge, no such manuscript ever turned up. It would have made interesting reading, yes?",
    "It was Neil Armstrong who made the first footprints on the lunar surface. Remember this, 'That's one small step for man, one giant leap for mankind'?",
    "No, it was Miss Clara Barton who did such wonderful work for Union soldiers in the Civil War, and who founded the American Red Cross. Florence Nightingale was certainly an 'angel of mercy' but not for her work in the American Civil War, but for her work with English soldiers during the Crimean War (1853-1856). ",
    "You have photic sneeze reflex. Photosynthesis is the way plants make food from sunlight.",
    "A crystal of zicron found by Simon Wilde, geologist at Curtin University of Technology in Perth, Australia, was dated at 4.4 billion years old. The Earth itself was only 160 million years old when the crystal was formed. His discovery was made in the outback of Australia. ",
    "Strawberries are known for their antioxidant properties all over, but they are also a rich source of vitamin C. Their vitamin C content is slightly more than that in a single orange.",

    "Angel Falls in Venezuela is the highest.",
    "It was first played in Germany.",
    "The San Diego Zoo does.",
    "Harvard opened its doors in 1636. William and Mary College in Virginia opened its doors in 1693.",
    "About 100,000 times a day.",
    "Also created by a woman were fire escapes.",
    "The cheetah is the fastest.",
    "Ruminant stomachs have four compartments: the rumen, the reticulum, the omasum and the abomasum. Rumen microbes ferment feed and produce volatile fatty acids, which is the cow's main energy source.",
    "Although Jamie Farr (Klinger) served in Korea it was in the late 1950s, long after the Korean War had finished.",
    "It was directed by Francis Ford Coppola. The Godfather Part II (1974) and The Lord of the Rings: The Return of the King (2003)is another film that has won an Oscar for Best Picture.",

    "Many man-made structures can be seen from outer space.",
    "While the UN Conference on International Organization began in San Francisco on 25 April 1945, no headquarters were established at the time.",
    "Shanghai is one of the four direct-administered municipalities of the People's Republic of China, It has the third-highest number of billionaires of any city in the world and highly ranked institutions",
    "Below is a list of the world's biggest countries in terms of area.\n#1 Russia: 17,075,200 km2 (6,591,027 mi2)\n#2 Canada: 9,984,670 km2 (3,854,082 mi2)\n#3 United States: 9,631,418 km2 (3,717,727 mi2)\n#4 China: 9,596,960 km2 (3,704,426 mi2)\n#5 Brazil: 8,511,965 km2 (3,285,618 mi2)",
    "A cygnet is a baby swan.",
    "It's orange and white.",
    "It actually stands for North Atlantic Treaty Organization.",
    "She was once married to the policeman.",
    "In 1999, the Padres and Rockies opened the season in Mexico.",
    "Kangaroo Rat: Believe it or not, this little animal can last longer without drinking water than any other. They go their whole lives (3-5 years) without drinking any! Technically, all these animals have to have water to survive; they just go a very long time without drinking it.",
    "The '57' represents the number of pickle varieties.",
    "Although popularized by the book 'Peter Pan', the name Wendy has been found in census records from as early as 1881, many years before J.M. Barrie used the name. Some sources indicate that, like Marian and Shirley, it was once a boy's name.",
    "A competition in Charlie Chaplin impersonations was held in California recently. There was something like 40 competitors, and Charlie Chaplin, as a joke, entered the contest under an assumed name. He impersonated his well known film self. But he did not win; he was 27th in the competition.",
    "He did this 100 years before the moons were even documented.",
    "Nope. Celery has practically no calories... so you burn while you eat it and that's about it.",
    "Actually they had to slow a movie down because he was so fast.",
    "Actually, it took him YEARS to paint the lips.",
    "This was due to the scarcity of metal.",
    "Orange and purple have no words that rhyme... at least, in the dictionary. Yet, brown does have words that rhyme with it.",
    "The Apollo 11 landing was July 20, 1969. \"DWW\" was released November 21, 1990, 21 years later. Pope Benedict resigned on February 28, 2013.",
    "A sheet of standard paper for copying and printing is about .01 cm thick. When you fold paper, the resulting number of layers grows exponentially. Folding nine times results in 512 layers, 20 folds reaches more than 10 km. It would take 42 folds to more than reach the moon. Don't bother to try to prove this yourself, though, because it's impossible to fold a piece of paper more than seven or eight times (feel free to try that). ",
    "Actually, on average, they're about two inches taller in space. This effect is the result of the lack of gravity which, on earth, compresses your spinal vertebrae. Once in space, the discs between the vertebrae decompress and you grow taller. ",
    "Using their Silbo Gomero whistling language, residents of La Gomera can communicate over distances as great as 5 km across their island. Whistling languages also exist in several areas of Africa, South America, Turkey, France and Mexico. As recently as the 1980s the entire population of the Greek village of Antia utilized their whistling language. Fewer than 40 residents now remain who know it.",
    "You're actually not bringing a killer into your house when you decorate for Christmas with the traditional red-leafed plant. If eaten, the leaves of Poinsettia will make some people a little sick to the stomach and rubbing a leaf into your eye can cause discomfort. A 50 pound child would have to eat about 500 leaves to ingest a toxic dose of the chemicals found in Poinsettia. ",
    "The human larynx sits lower in the throat than in other primates. This gives us the ability to create the wide range of sounds needed for speech, but it also makes it impossible for us to breathe while swallowing - something many other animals can do. The larynx doesn't drop until about age nine months so human infants are able to breathe while nursing. ",
    "Thank goodness for small favors! This rumor started in 2011 when plastic surgeon Dr. Anthony Youn wrote a blog entry for CNN.com entitled \"Smoking can make your nipples fall off\". Hard to imagine how that would cause confusion or concern. What Dr. Youn actually says is that patients for breast enlargement or reduction who smoke in the weeks prior to and after the surgery run a small risk of having their nipples turn black and falling off. The nicotine and carbon monoxide in the tobacco smoke restrict blood flow to the affected area, causing necrosis.",
    "The penny would reach a terminal velocity of about 50 mph or less which isn't nearly fast enough to kill anyone. At most it would sting somewhat. In contrast, a skydiver's terminal velocity is 130 to 150 mph.",
    "Actually you can't get warts from toads (or frogs). Warts are caused by the human papillomavirus which is unique to humans. So you can get a wart by shaking hands with someone who has a wart.",
    "Color vision is a function of cone photoreceptors within the retina. A human's central retina is 100% cones while a dog's central retina consists of about 20% cone receptors. Recent tests in dogs suggest that they can distinguish red and blue colors but often confuse green and red.",
    "Yes, Russia is big. And Pluto isn't. Russia's surface area is 17,125,187 square kilometers, while Pluto is only 16,647,940 square kilometers. ",
    "This myth was detailed in a 1958 Disney feature \"White Wilderness\" which featured a segment on lemmings, explaining their strange compulsion to commit mass suicide. Unfortunately, scientists say that lemmings have no suicidal desires and a 1983 investigation showed that Disney producers faked their depiction of lemming mass suicide. \"White Wilderness\" won an Academy Award for Best Documentary Feature.",
    "Octopus also have nine brains and blue blood. By the way, the plural of octopus is not \"octopi\". \"Octopi\" would be fine if the word was a Latin derivative but \"octopus\" is of Greek origin. If you insist on the Greek plural, go with \"octopodes\". But, since \"ocotopus\" has been adopted into English, the best choice is probably to treat it as an English word and use the plural \"octopuses\".",
    "McLobster (lobster meat and shredded lettuce on a hot dog bun with \"McLobster Sauce\") was test marketed nationally without much success. The $5.99 price might have contributed to its failure. It still appears periodically as a short term special item on McDonald's menu in parts of New England and eastern Canada.",
    "Actually chewing gum (classified by the FDA as a \"nonnutritive masticatory substance\") doesn't digest at all. The gum passes through your digestive system pretty much unchanged in far less than seven years.",
    "Earth's orbit isn't a circle, but an ellipse. Its closest point is about 5 million km closer to the sun that its furthest point. That distance is not enough to cause our seasonal changes, though. The seasons are caused by the tilt of the Earth on its axis.",
    "Nancy Hanks Lincoln died at the family's cabin in Spencer County, IN on October 5, 1818. She is generally thought to have been the victim of \"milk poisoning\", a condition which was epidemic in the area at the time of her death. Other causes for her death have been proposed, such as TB, but fear of a return of \"milk sickness\" played a part in the family's decision to move from the area.",
    "In 1925, the Eiffel Tower was rusting and in need of very expensive maintenance and repairs. As the tower had been built for the Paris Exposition of 1889 and was only meant to last for 20 years, the French government and people were divided as to whether the tower should be preserved or torn down.",
    "Astronomers estimate that the Milky Way Galaxy contains something more than 200 billion stars. Neuroscientists estimate, though, that a three year-old child's brain contains close to 1 quadrillion synapses. That number falls by half, to about 500 trillion in an adult.",
    "Amazingly true! US Patent # 121992, Dec. 19, 1871 was granted to Samuel L. Clemens of Hartford, CT for \"Improvement in Adjustable and Detachable Straps for Garments\". Twain describes, \"The nature of my invention consists in an adjustable and detachable elastic strap for vests, pantaloons, or other garments requiring straps.\" ",
    "A blue whale's sound has been measured at 188 decibels. Elephants don't even place second in the animal noise competition. That honor belongs to the South American Howler Monkey.",
    "Like other cetaceans, narwhals communicate via clicks and whistles. Recent research indicates that the tusk may be used as a sensor to tell the narwhal about its surroundings. The tusk is porous and filled with nerves which could transmit data such as water temperature, pressure and salinity to the animal's brain.",
    "Harvard, America's oldest college, was founded in 1636. Calculus was developed about 50 years later by Gottfried Leibniz's 1684 \"Nova Methodus\" and Isaac Newton's 1687 \"Principia\" as well as refinements by by other mathematicians over the years. ",
    "The position is so named due to the player's extreme proximity to the batsman, making the position as dangerous as it is silly. This is the extent of my knowledge of the game of cricket.",
    "There are actually four such words. The fourth is \"hazardous\".",
    "Peter Durand, a British merchant, was granted a patent for the tin can in 1810. Opening his invention remained a problem, though, until 1858 when American Ezra J. Warner patented the first practical can opener.",
    "Actually we humans only share about 50% of our DNA with bananas and plantains. To reach the 90% level you'd have to compare humans to chimpanzees or other primates.",
    "From 1939 to 1941 the Sea Floor post office operated in the Bahamas. The \"biosphere\" post office was the idea of US underwater photographer John Ernest Williamson. Covers postmarked at the Sea Floor office are quite collectible and valued as high as $300. ",
    "\"Reagan as Rick\" is a widely heard rumor but the truth is quite different. The part of Rick Blaine was actually written for Humphrey Bogart. Prior to \"Casablanca\" Bogart had been cast almost exclusively as a gangster, usually as a villain. Hal Wallis, the film's producer wanted Bogie for the role of Rick so he told Warner Brothers the part was written for him.",
    "The Aleutian Islands straddle the 180 degree line of longitude, placing them at the very edge of both the Eastern and Western Hemispheres. "
    "Nocturnal refers to animals that are usually more active during the night than the day. ",
    "Cats seem to respond to the colors purple, blue, green, and yellow with blue and green being the strongest colors they perceive. Red, orange, and brown colors appear to fall outside a cat's color range and are believed to be seen as shades of gray or purple.",
    "A carnivore means a true meat-eating animal, and our feline friends are classified as true carnivores because they MUST consume meat in order to survive.",
    "Yes, they do. They're not too far above the paw pads and they're shorter than the ones found around the face.",
    "The cat's sense of smell is its primary source for identifying the individuals and objects in its environment. They have 200 million odor-sensitive cells in their noses compared to only 5 million for humans.",
    "Despite the name, ringworm is not a worm but a fungal disease. One of the most common skin problems of cats, ringworm invades the hair follicle. The name, ringworm, comes from the appearance of the skin lesion. A red ring outlines a circular patch of scaly skin and broken-off hairs.",
    "Cats do sometimes breathe through their mouths. For example, if they've been running around playing or chasing something, they may need a minute to catch their breath.",
    "At lower-pitched sounds, there is little difference between humans and cats (and dogs). At the higher sounds, humans can hear up to approximately 20,000 cycles per second. Dogs can hear sounds of frequencies of up to 35,000 to 45,000 cycles.",
    "Chocolate contains an ingredient called theobromine that is very toxic to cats which can affect four areas of the cat's body. It can increase the cat's heartrate, it can act as a diuretic causing the cat to lose body fluids, it can affect the gastrointestinal system causing vomiting and diarrhea and could also cause stomach ulcers. And, it can act on the nervous system causing convulsions, seizures and sometimes even death.",
    "Cats can use their whiskers for several things and one of them is to detect sizes of openings. A cat's whiskers grow accordingly to accommodate the cat in perceiving whether or not it can easily pass through something such as a passageway, or if it may become stuck. Other uses of the whiskers are a cat's way to indicate their mood and for the catching of prey",
    "No, because there is potential harm that can affect a cat being restrained by the scruff. Based on the research I've done, I've found that picking cats up by the scruff can cut off their oxygen supply and put strain on their neck muscles when their hind quarters are in a dangling-like position, and they're carried in this manner for substantial distances.A veterinary nurse did inform me, however, that picking cats up by the scruff is considered common practice as long as the cat isn't carried that way for too long of a distance. Also, if you're able to support the hind quarters of the cat while holding it by the scruff, this is considered a safe way of handling a cat by its scruff. ",
    "Cats do not have enough necessary enzymes in the liver to allow normal metobolization of aspirin; therefore, resulting in a very slow break down process of the aspirin which can lead to toxicity levels and possibly even death when given more frequently than once every 48 hours at a dosage of more than 81 mg.",
    "Stud tail is an infection on a cat's tail caused from overproducing sebacceous glands. It's seen more often in unaltered males and the tail appears dirty and greasy and gives off an odor. Treatment for this condition can include washing the tail in a medically prescribed shampoo on a regular basis. Also, antibiotics or even surgery may be required if there's inflammation, and neutering of the intact cat is recommended.",
    "Yes, this is true. Feline acne is most commonly found on the cat's chin appearing as blackheads or pimples. There seem to be many beliefs about the causes of feline acne which vary from food allergies, contact allergies, and some experts even believe stress may play a part. This condition is also believed to be caused by lack of grooming to the chin where dirt and oil can accumulate and cause the hair follicles to become clogged. The most common belief, however, is that cats who eat and drink out of plastic bowls may be more prone to this condition simply because plastic is supposedly more difficult to keep clean. For me, my cats have always been given their food and water in plastic bowls for which I have had no problems keeping clean. And so far, they've never had any problems with feline acne either",
    "Feline AIDS, also known as Feline Immunodeficiency Virus (FIV), has similarities to that of the human AIDS virus but is not the same virus. From my research, I found that most viruses are species specific, meaning that the AIDS virus only affects humans and the FIV only affects cats. Well, I hope you liked the quiz and possibly learned some new facts concerning cats, I know that I sure did when creating it.",
    "Alexander the Great was born in Macedonia. He was also known as \"Alexander III\" and was King of Macedonia during the period: 336-323 BC.",
    "Rectangles have opposite equal sides, and their diagonals will always bisect each other.",
    "In 1960, Harper Lee's novel won the Pulitzer Prize. ",
    "The Chinese Tiger is very near extinction, whilst the Sumatran, Siberian, and Indian subspecies are also listed as endangered.",
    "Lawn Bowls is a popular outdoor game in which a ball, commonly called the \"bowl\", is rolled along the ground toward a smaller ball, called a \"jack\". ",
    "The Disposable Heroes of Hiphoprisy" were an excellent band which was fronted by Michael Franti. Their album release "Hypocrisy Is The Greatest Luxury" included songs such as "Television the Drug of the Nation" and \"The Language of Violence.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",












  };

  char trueOrFalseAnswers[200] = {
    'T','T','T','T','T','T','T','T','T','F',
    'T','F','F','T','T','T','T','T','F','T',
    'T','T','T','T','T','T','T','T','T','T',
    'F','T','F','T','F','T','F','T','F','F',
    'F','F','F','F','F','F','T','F','T','T',
    'T','T','T','T','F','F','F','F','F','F',
    'F','T','F','T','F','F','T','T','F','T',
    'T','F','T','T','F','F','F','F','T','T',
    'F','F','F','T','F','F','F','F','T','T',
    'F','F','T','T','F','F','F','T','F','T',
    'F','F','F','T','F','F','F','T','T','T',
    'T','T','F','T','F','F','T','T','F','T',
    'F','T','T','T','F','F','F','T','T','F',
    'T','F','T','F'




  };
};

#endif // QUESTIONSTRUEORFALSEANDTRIVIA_H
