#ifndef TRUEORFALSEQUESTIONS_H
#define TRUEORFALSEQUESTIONS_H
#include <QString>

class trueOrfalseQuestions
{
public:
  trueOrfalseQuestions();
  ~trueOrfalseQuestions();
QString getQuestion(int index);
QString getExplanation(int index);
char getAnswers(int index);
QString getLivesPicture();
private:
QString livesPicture = "background-repeat:no-repeat;background-image: url(:/bGrounds/backgrounds/h11.png);";
  QString questions[195] = {
    "The capital of Michigan is Lansing. ",
    "The movie \"The Runaway Bride\" and \"Pretty Woman\" both star at least three of the same actors/actresses.",
    "The movie \"American Beauty\" won the Oscar for Best Picture.",
    "The birthstone for September is the sapphire. ",
    "The following books are in the Old Testament of the Bible: Genesis, Exodus, Numbers and Leviticus. ",
    "George Burns, the actor, lived to be 100 years old.",
    "The word \"right\" has 5 letters in it.",
    "There are more than 100 quizzes on FunTrivia site.",
    "The word \"Amore\" in Italian means \"Love\" in English.",
    "Toronto is the capital of Canada.",

    "Sylvester Stallone has been nominated for both an Academy Award for 'Best Actor' and a Razzie Award for 'Worst Actor' for playing the same role.",
    "'Call Me Ishmael' is the first line of the book 'Tom Sawyer'. ",
    "In the US version of the game 'Monopoly', the color of Vermont Avenue is dark blue. ",
    "In tennis, The Australian Open is one of the four tournaments making up the Grand Slam.",
    "Before becoming Governor of Texas, George W. Bush was co-owner of a professional baseball team. ",
    "An elephant can smell water up to 3 miles away.",
    "The TV Show 'All in the Family' is based on a British TV Show.",
    "The doctor who tended to John Wilkes Booth after he shot Abraham Lincoln's name was Mudd.",
    "Dennis the Menace's favorite beverage is water.",
    "The Lone Ranger's horse was named Silver.",

    "The Lone Ranger's real name was John Reid before becoming The Lone Ranger. ",
    "Tonto's horse was called Scout.",
    "Leo is the name of the MGM lion.",
    "Lennie and George were the main characters in Steinbeck's 'Of Mice and Men'. ",
    "Captain Kirk slept on Deck 5 in the T.V. series 'Star Trek'. ",
    "President F. D. Roosevelt declared December 7, 1941 'a date which will live in infamy'. ",
    "Chester, on 'Gunsmoke' had the last name of Proudfoot. (radio version)",
    "Paladin carried a Colt .45.",
    "Zip stands for Zone Improvement Plan.",
    "Lindsay Wagner played 'The Bionic Woman' in the T.V. series.",

    "Billy the Kid's real name was William H. Bologna.",
    "Billy Joe McAllister jumped off the Tallahatchie bridge.",
    "Over 1,000 Americans died at the Alamo.",
    "Alfred was Bruce Wayne's butler on the T.V. series 'Batman'.",
    "Pancho's horse was Lobo. Remember, he was The Cisco Kid's partner.",
    "Judy Jetson went to Orbit High School. ",
    "Tellus was the first U.S. communications satellite.",
    "Socrates taught Plato.",
    "Trieste Boy was Roy Roger's horse.",
    "When Pete Rose played for the Cincinnati Reds his number was 0.",

    "If you mix Jack Daniels and Jim Beam together you are making a gin and tonic.",
    "George Washington is noted for having almost perfect teeth.",
    "Robert E. Lee commanded the Army of the Potomac during the Civil War.",
    "George Jefferson was the President of the Confederate States during the Civil War.",
    "John Ritter was the father of Tex Ritter.",
    "The dog, Rin Tin Tin was actually a female dog.",
    "The Righteous Brothers' real names were Hatfield and McCoy.",
    "When the Jolly Green Giant first appeared on commercials he was actually the Jolly Yellow Giant. ",
    "The Galloping Spook was Red Grange's nickname when he played football.",
    "The Super Mex is the nickname of pro-golfer Lee Trevino.",

    "'The Texas' chased 'The General' in the Great Locomotive Chase in the Civil War.",
    "The 'Texas Theatre' was the Dallas movie house where Lee Harvey Oswald was captured after the shooting of J.F.K.",
    "'The Buck Stops Here' was the saying on the sign on President Truman's desk. ",
    "Terrytown was where Mighty Mouse lived.",
    "Fisher was the man's last name who appeared on the first U.S. postage stamp.",
    "Fred was the man's last name that coined the phrase, 'Rock and Roll'.",
    "Freeport was Mr. Wilson's pet dog on 'Dennis the Menace'.",
    "Fritzie was the name of William S. Hart's horse.",
    "Fryer was the name given to the Wright Brother's airplane.",
    "It is impossible to get a McDonald's Happy Meal in New Delhi, India.",

    "Women athletes competed with male athletes in the Ancient Greek Olympic Games.",
    "The first warship sunk by a submarine was during the American Civil War, when the Confederate sub 'Hunley' sunk the USS 'Housatonic'.",
    "King Akhenaten of Egypt was considered even more beautiful than his wife, Queen Nefertiti. ",
    "The first Triceratops bones were discovered in 1889.",
    "Chocolate syrup was used to simulate blood in the old 1931 vampire classic 'Dracula' by Universal starring Bela Lugosi.",
    "Two days before Anthony Porter was to be executed for a double murder, he was granted a stay when students re-enacting the case discovered the real killer. ",
    "In 1775, Davey Crockett blazed the Wilderness Trail travelled by pioneers across the Appalachians of North Carolina through the Kentucky mountains.",
    "If you are allergic to live animals, don't worry. You can adopt a mummy animal from Egypt's Cairo Museum.",
    "Adults have more bones than babies do. ",
    "In 1837, a law was passed by the United States Congress that every seagoing ship must carry a life preserver for every passenger.",

    "The biggest known volcano in the solar system is on Mars.",
    "Wilbur Wright died in 1908 of injuries he suffered when the protoype airplane, that he and his brother Orville had developed for the United States Army, crashed near Ft. Meyers, Virginia.",
    "The macaroni penguin of Antarctica gets its name from the old American Revolutionary war song 'Yankee Doodle'. ",
    "During the American Civil War, one of Confederate Gen. Kirby's Smith's officers received a coded message so complex, he had to ride around Union lines to ask the sender what in the heck he was saying. ",
    "Found among Robert Louis Stevenson's effects after his death, was the original manuscript of 'Treasure Island' (rejected by his publisher) in which Stevenson reveals that Jim Hawkins's real father was Long John Silver.",
    "On July 20, 1969, American astronaut Alan Shepherd made the first footsteps ever on the surface of the moon.",
    "Florence Nightingale was known as the 'angel of mercy' for her ministrations to Union soldiers in the American Civil War, and for her tremendous efforts in founding the American Red Cross. ",
    "If you sneeze when suddenly exposed to intensely bright light, you have photosynthesis.",
    "The oldest rock on Earth was found by geologists in the outback of Australia in January, 2001.",
    "Strawberries have more Vitamin C than oranges.",

    "Niagara Falls is the highest waterfall in the world.",
    "Bowling was first played in Italy.",
    "The Los Angeles Zoo has the largest collection of animals.",
    "Harvard is the oldest college in the United States.",
    "On average, the 'eye muscles' move 300,000 times a day.",
    "The bulletproof vest was created by a woman.",
    "The leopard is the fastest mammal on earth.",
    "Cows have four-chambered stomachs.",
    "No cast member on 'M*A*S*H*' served in the Korean War.",
    "The first sequel to win Best Picture at the Academy Awards was 'The Godfather Part II'. ",

    "The only man-made structures that can be seen from outer space are the Great Pyramids. ",
    "The United Nations was originally headquartered in San Francisco.",
    "Shanghai was once the largest city in the Communist world.",
    "Canada is the second largest country in terms of size/area.",
    "A cygnet is a baby dolphin.",
    "The official ball for the WNBA (Women's National Basketball Association) is red, white, and blue.",
    "NATO is an acronym for 'North American Treaty Organization'.",
    "Phylicia Rashad (Mrs. Huxtable on 'The Cosby Show') was once married to a member of the Village People.",
    "In 2000, The Mets and Cubs opened the Major League baseball season in Japan. This marked the first time that the baseball season has opened in a country other then the United States or Canada.",
    "A rat can last longer without water than a camel.",

    "The '57' on the Heinz ketchup bottle represents the number of varieties of tomato the company once used.",
    "Before the book 'Peter Pan', the name Wendy had never been used.",
    "Charlie Chaplin once won third prize in a Charlie Chaplin look alike contest.",
    "In 'Gulliver's Travels', Jonathan Swift described the two moons of Mars, Phobos and Deimos, giving their exact size and speeds of rotation.",
    "Celery has so many calories that eating it isn't even a workout.",
    "Bruce Lee was so slow while going through his moves that they had to speed up one of his movies to make it look real.",
    "It took Leonardo da Vinci ten days to paint Mona Lisa's lips.",
    "During World War II, the Oscars were made of plaster.",
    "There are no known English words that rhyme with orange and purple.",
    "The human race has managed to exterminate only two species of insects.",

    "Henry Ford's profit on his Model T Ford was only about $2.00.",
    "All the bones in the human body connect to one another.",
    "The great Otto Preminger, once said of Walt Disney, \"He has the greatest control of his cast in a film, if a character doesn't fit he just tears it up.\"",
    "With all the great songs that have come out of all the Disney movies, there has never been a Disney song that made it to number 1 on the charts. ",
    "There are no civilians buried in the West Point Cemetery.",
    "Hollywood has never released a movie that had it's sequel releasedthe same year",
    "The Republican Party GOP initials originally stood for \"get out and push\".",
    "Students who enter the United States Air Force Academy make a commitment to the Air Force of at least 9 years. ",
    "True Roquefort cheese is made from ewe's milk.",
    "Golden retrievers are the world's most popular breed of dog (in numbers purchased).",

    "Stalactites come up from the ground.",
    "There is NOT a Dr. Pepper bottling plant in Plano, Texas.",
    "In 'Romeo and Juliet', Tybalt kills Benvolio.",
    "In golf, the International team won the year 2000 President's Cup.",
    "Sacagawea is on the US silver dollar.",
    "The language with the most native speakers in the world is Chinese.",
    "Bill Gates is the CEO of Dell Computers.",
    "The contrabassoon is a percussion instrument.",
    "Garry Kasparov was the top chess player in the world at the end of the year 2000.",
    "A standard guitar has 5 strings.",

    "Guatemala is located in South Africa.",
    "Ali Landry is better known as the Doritos Girl.",
    "As of the year 2000, Pat Riley led active NBA head coaches in total playoff victories.",
    "Your ears and your nose lengthen throughout your life.",
    "As of the year 2000, the U.S. stock market, for a period of the past 70 years, averaged an annual return of 5 percent.",
    "C.C. Deville plays lead and rhythm guitar for the band Poison.",
    "To 'plead the 5th' is to refuse to allow law enforcement officials to search your car or household.",
    "APR means annual percentage ratio.",
    "The average number of people who will get cancer at some point in their lives is 15 in 100.",

    "\"Damn it. Don't you dare ask God to help me.\" These were the last words spoken by Bette Davis on October 6, 1989.",
    "No United States President has ever been elected unanimously.",
    "Walt Disney had a job on a railroad.",
    "Gabriel and Michael were the only two angels, mentioned by name, in the King James Bible? ",
    "A zebra is really white with black stripes. ",
    "Elizabeth June Thornborg was an actress in the movie \"Annie Get Your Gun\". ",
    "The tin can was invented before the tin can opener. ",
    "In 1936, Ray Brennan was the last person to be publicly executed in the United States.",
    "Bob Keeshan (Captain Kangaroo) also played Clarabelle on \"The Howdy Doody Show\".",
    "Selachophobia is the fear of light flashes.",
    "In the 1890s, Harvard and Army were the first colleges to adopt animal mascots.",

    "\"Alexander the Great\" was once the King of Macedonia.",
    "Diagonals drawn from opposing corners of a rectangle will always bisect each other.",
    "Harper Lee won the Pulitzer Prize for the novel \"To Kill A Mockingbird.\"",
    "Only the Chinese Tiger is an endangered tiger species.",
    "There are two main types of balls in the sport of Lawn Bowls: the \"bowl\" and the \"jack\".",
    "Michael Franti used to be the main singer in the band \"The Disposable Heroes of Hiphoprisy\"",
    "The film \"The Princess Bride\" was released in 1984.",
    "On Ernest Shackleton's famous South Pole expedition (1914 - 1916), the ship they set out on was called the \"Endurance\".",
    "The \"Lumbar Curve\" is located in the leg on the human body.",
    "The painting \"The Persistence of Memory\" was a product of the artist Picasso.",
    "Saint Patrick, the patron saint of Ireland, was not born in Ireland.",
    "Alchemy is a philosophical system founded on the principle of trying to transform base metals into more rare metals.",
    "In the English version of the game \"Monopoly\", Old Kent Road is the highest selling property.",
    "Traditionally, the amethyst gemstone is the birthstone for the month of August.",
    "The man who is considered responsible for inventing the mouse, Douglas Engelbart, never patented his idea.",

    "Children do not suffer from depression.",
    "Depression is a common illness.",
    "Exercise can help some forms of depression.",
    "Change in season can bring on some forms of depression.",
    "You have to feel depressed to have depression.",
    "A depressed person living in a home with a gun in it is more likely to commit suicide than one in a home without a gun.",
    "Schizophrenia and Bi-Polar Disorder are the same thing.",
    "Bi-Polar Disorder and Manic Depression are the same thing.",
    "More women than men are likely to suffer from depression.",
    "There are several treatments for depression.",
    "Joshua Slocum was the first person to sail around the world single-handed.",
    "A small baby cannot blush.",
    "The blue whale, the world's largest creature, has the biggest eye in the animal kingdom, roughly the size of a large dinner plate.",
    "The first major motor race run in the British Isles was the Gordon Bennett Trophy of 1903.",
    "A teaspoon of ground coffee contains more caffeine than a teaspoon of tea leaves.",
    "Sudd is a name given to a swampy area in Sudan.",
    "British actor Stewart Granger's real name was James Stewart.",
    "The Queen normally faces right on British postage stamps.",
    "The 'Laughing Cavalier' was painted by Rembrandt. ",
    "The martial art of tae kwon do originates from Japan.",
    "The first living creatures to fly in a hot air balloon were a duck, a sheep and a rooster. ",
    "In 1968, Graham Hill became the first British racing driver to win the World Championship.",
    "Spinach, Popeye's favourite food, contains roughly 10 times the iron content of any other vegetable.",
    "William Shakespeare was the first Poet Laureate.",
    "The Trans-Siberian railway line is the longest in the world. ",
    "Everyone can conquer depression by thinking happy thoughts and keeping busy.",
    "There is more than one type of depression.",
    "Some types of depression run in families.",
    "Men do not suffer from depression.",
    "Antidepressant drugs are sedatives."



};

QString explanations[195] = {
    "There are numerous cities in Michigan, including Holland where we celebrate the Tulip Time Festival every year. There is also the city of Detroit. \"Go, Go, Go Detroit Lions!\"",
  "Yes, both of these movies star the handsome Richard Gere, the beautiful Julia Roberts and the entertaining Hector Elizondo. Hector has been in numerous movies, including his dance scene with Julie Andrews in \"The Princess Diaries\".",
  "I don't get it. \"American Beauty\" wins Best Picture, beating out \"The Green Mile\" and \"The Sixth Sense\". Don't misunderstand me. I like Kevin Spacey. I adored Annette in \"The American President\", but \"American Beauty\"? Am I clueless here?",
  "Yes, the beautiful blue sapphire is the gem for the month of September. Actually September is a pretty cool month. In the United States, we celebrate the holiday, Labor Day, in September. The kids also go back to school around this time. We also get to welcome the season Fall in too.",
  "Genesis would be the first book in the Old Testament. Matthew is the first book in the New Testament. Matthew is followed by Mark, Luke and John too. Now, the last book of the Bible would be Revelation. Do you remember the song, \"The B I B L E... yes, that's the book for me, I stand alone on the word of God, the B I B L E.\" ",
  "George Burns was born in the bright city lights of New York, New York in 1896, in January. George and his wife, Gracie entertained audiences for many years. George passed away and left us in March of 1996 in Beverly Hills, California. From coast to coast, you left your mark, George. Thanks!",
  "You are right about this. Not to be confused with writing a letter though. You could say that she was right or wrong too. Maybe I'll just turn right to the next question here. Right?",
  "Yes, there's literally thousands of quizzes on this site. The quizzes are actually played by thousands of players too. We even have thousands of authors too. But, we only have a handful of editors. Remember, treat those editors with lots of kindness. They volunteer their time just for you!",
  "If you ever have seen the movie \"Moonstruck\" with Cher, this word is used quite often. \"Amore\" is in the air. \"Amore\" is in the moon. \"Amore\" is all around. Cher won the Oscar for Best Actress for this movie.",
  "Ottawa is the Capital of Canada. Toronto is the Capital of Ontario.",

  "Yes, he was nominated for 'Best Actor' in Rocky and 'Worst Actor' for Rocky V, playing the same role of Rocky Balboa.",
  "It's the first line to the book 'Moby Dick'.",
  "Its color is light blue. Boardwalk and Park Place are dark blue.",
  "The Australian Open, The French Open, Wimbledon, and The US Open comprise the Grand Slam in tennis.",
  "He was a co-owner of the Texas Rangers.",
  "Elephants have a keen sense of smell, detecting water sources up to 19.2 km (12 mi.) away. Nostrils are located at the tip of the trunk and function in breathing, smelling, and drawing water in to squirt into the mouth. ... Turbinals are curls of bone that have millions of olfactory receptor cells associated with them.",
  "It is based on the TV Show 'Til Death Us Do Part.'",
  "Samuel A. Mudd, the Maryland doctor who treated John Wilkes Booth, who had broken his left leg in the jump to the stage after shooting Lincoln.",
  "His favorite is root beer.",
  "Debut WXYZ on Detroit radio January 30, 1933.",

  "Created by Fran Striker and George W. Trendle.",
  "Tonto actually gave The Lone Ranger his famous name.",
  "Leo (1957–present) Leo, the seventh lion, is by far MGM's longest-used lion, having appeared on most MGM films since 1957. Leo was born in Dublin Zoo, Ireland, the same as Slats. He was also the youngest at the time MGM filmed him roaring, hence his much smaller mane.",
  "They were Lennie Small and George Milton.",
  "So did Mr. Spock, Dr. McCoy and Mr. Scott.",
  "Roosevelt changed \"a date which will live in world history\" to \"a date which will live in infamy,\" providing the speech its most famous phrase and giving birth to the term, \"day of infamy,\" which December 7, 1941, is often called. ",
  "Chester was played by Parley Baer on radio, and by Dennis Weaver on television. Chester's character had no surname until Baer ad libbed \"Proudfoot\" during an early rehearsal. Initial Gunsmoke scripts gave him no name at all; his lines were simply to be spoken by \"Townsman\".",
  "Have Gun - Will Travel was a Western television series that starred Richard Boone as a gunfighter who calls himself \"Paladin\" and traveled throughout the West, using his revolver to right wrongs for those who come to hire him. The half-hour series aired in the US on CBS from 1957 to 1963 and several of the writers from the series would come to be well known in the business, including Star Trek's Gene Roddenberry. In addition, 101 episodes were directed by Andrew V. McLaglen. ",
  "Introduced in 1962. So how well did you do? I sure hope you got 10/10 as I gave away still another clue as to how this quiz should be answered. Thanks for taking my quiz. Kabel :)",
  "She was injured in a skydiving accident and they made her bionic.",

  "William H. Bonney was his real name.",
  "\"Ode To Billy Joe\" by Bobbie Gentry.",
  "By all the accounts I have managed to look up it was more like 188 men that died fighting the Mexicans.",
  "Batman (1966 TV) Alan Napier as Alfred Pennyworth, played Batman's loyal butler.",
  "The Cisco Kid is a 1950-1956 half-hour American Western television series starring Duncan Renaldo in the title role, the Cisco Kid, and Leo Carrillo as the jovial sidekick, Pancho. The series was syndicated to individual stations, and was popular with children.[1] Cisco and Pancho were technically desperados wanted for unspecified crimes,[2] but were viewed by the poor as Robin Hood figures who assisted the downtrodden when law enforcement officers proved corrupt or unwilling to help.[3] It was also the first television series to be filmed in color,[4] although few viewers saw it in color until the 1960s. ",
  "The following is a list of major characters in The Jetsons, an American animated comic science fiction sitcom produced by Hanna-Barbera Productions and first broadcast in prime-time on ABC as part of the 1962–63 United States network television schedule. Additional episodes were produced from 1985 to 1987 in syndication, with the same cast of characters. ",
  "On July 10, 1962, AT&T Bell Telephone Laboratories (now Nokia Bell Labs) and NASA launched Telstar 1, the first communications satellite from Cape Canaveral. Global communications changed forever.",
  "His most famous student was Plato (l. c. 428/427-348347 BCE) who would honor his name through the establishment of a school in Athens (Plato's Academy) and, more so, through the philosophical dialogues he wrote featuring Socrates as the central character.",
  "Nope, it was Trigger. Did you figure out the pattern? If you did then you got 10/10 and bettered your scoring. Hey, if you like my goofy way of doing T or F quizzes, drop me a line. Thanks Kabel :)",
  "CINCINNATI -- Reds great Pete Rose's No. 14 has been informally out of circulation for decades. Since 1963, the only other player to wear No.",

  "Actually I think you are making a good hangover. ",
  "Actually he had an awful lot of problems with his teeth. There is a painting of him in the Cincinnati Art Museum sporting his famous wooden teeth.",
  "Robert Edward Lee (January 19, 1807 – October 12, 1870) was an American Confederate general best known as a commander of the Confederate States Army during the American Civil War. He commanded the Army of Northern Virginia from 1862 until its surrender in 1865 and earned a reputation as a skilled tactician.",
  "Jefferson Finis Davis (June 3, 1808 – December 6, 1889) was an American politician who served as the president of the Confederate States from 1861 to 1865.",
  "Jonathan Southworth Ritter (September 17, 1948 – September 11, 2003) was an American actor and comedian. He was the son of the singing cowboy star Tex Ritter and the father of actors Jason and Tyler Ritter.",
  "Rin Tin Tin (often hyphenated as Rin-Tin-Tin; September 1918 – August 10, 1932) was a male German Shepherd who was an international star in motion pictures. He was rescued from a World War I battlefield by an American soldier, Lee Duncan, who nicknamed him \"Rinty\".",
  "Robert Lee Hatfield (August 10, 1940 – November 5, 2003) was an American singer. With Bill Medley, he was part of the Righteous Brothers. He sang the tenor part for the duo, and sang solo on the group's 1965 recording of \"Unchained Melody\". ",
  "Green Giant and Le Sueur are brands of frozen and canned vegetables owned by B&G Foods.The company's mascot is the Jolly Green Giant. ",
  "In the second half he scored a fifth touchdown and threw a touchdown pass in a 39–14 Illinois victory. Grange was nicknamed the “Galloping Ghost” for his blinding speed and elusive running style.",
  "He is an icon for Mexican Americans, and is often referred to as \"The Merry Mex\" and \"Supermex,\" both affectionate nicknames given to him by other golfers.",

  "The Great Locomotive Chase (also known as the Andrews' Raid or Mitchel Raid) was a military raid that occurred April 12, 1862, in northern Georgia during the American Civil War. Volunteers from the Union Army, led by civilian scout James J. Andrews, commandeered a train, The General, and took it northward toward Chattanooga, Tennessee, doing as much damage as possible to the vital Western and Atlantic Railroad (W&A) line from Atlanta to Chattanooga as they went. They were pursued by Confederate forces at first on foot, and later on a succession of locomotives, including The Texas, for 87 miles (140 km). ",
  "The Texas Theatre is a movie theater and Dallas landmark located in the Oak Cliff neighborhood of Dallas, Texas. It gained historical significance on November 22, 1963, as the location of Lee Harvey Oswald's arrest over the suspicion he was the killer of Dallas Police Officer J. D. Tippit.",
  "\"The buck stops here\" is a phrase that was popularized by U.S. President Harry S. Truman, who kept a sign with that phrase on his desk in the Oval Office. The phrase refers to the notion that the President has to make the decisions and accept the ultimate responsibility for those decisions.",
  "Mighty Mouse is an American animated anthropomorphic superhero mouse character created ... In The Green Line (1944), the cats and the mice live on either side of a green dividing line down the middle ... Terrytown is the setting for this need for Mighty Mouse to rescue the mice who are threatened by a gang of alley cats.",
  "Franklin was his name. Benjamin Franklin to be exact.",
  "Freed was his name. Alan Freed to be exact.",
  "Nope, it was Fremont.",
  "No, it was Fritz and he lived to be 31 years old.",
  "Flyer would have been the correct answer. Did you notice the 'clue' given in each statement? The first five questions all started with a 'T' and the last five with an 'F'. Oh what will Kabel come up with next!?",
  "Cows are sacred in much of India. Cow dung is burned for fuel and used for fertilizer. Cow's milk can be drunk. You can get a McDonald's Happy Meal, but the burger is going to be a 'lamb-burger'.",

  "Married women were not allowed to compete or attend the Ancient Greek Olympic Games. Since most girls were married at about 13 years old, very few spectators were female. But there were games for women athletes held in Olympia and throughout Greece. The Heraea Games, named after the god Zeus' wife Hera, featured foot races along a 525-foot track. Since men competed in the nude (remember all those Grecian statues and vases) there wasn't a chance of a lady in disguise slipping in the events at the Ancient Olympic Games.",
  "On Feb.17, 1864, the Confederate sub 'Hunley' rammed 90 pounds of gunpowder into the Union Navy ship 'Housatonic'. Within five minutes, the ship and its 155 member crew went to the bottom. The victory really seems a hollow one, doesn't it, as the 'Hunley' also was sunk.",
  "Actually, images of Akhenaten found in the early 1880s in his tomb at el-Amarna show the Pharaoh had a large head, narrow chin, and a thin neck. While this might not sound too unattractive, he is often depicted as having large breasts, big hips, and thin arms and legs, which some experts think was caused by a genetic disease. Akhenaten started his reign as Amenhotep IV, but changed his name in the fifth year he was king. The name Akhenaten means 'Aten is on the horizon', Aten being the sun.",
  "Yes, and quite a find it was, too, for one of America's most respected paleontologists, Othniel Charles Marsh. Marsh was a professor at Yale University, and head of Yale's Peabody Museum. The find was made in Wyoming at Como Bluff. He may be as well remembered for his rivalry with another fossil hunter, Edward Drinker Cope, as he is for his fabulous finds. Before the two became enemies in their 'Bone Wars', they invented the 'plaster jacket' still used today by paleontologists to transport their finds from the digs.",
  "Nope. There wasn't actually any blood shown in the 1931 classic. The scares came from Lugosi's wonderful campy Count, a fine supporting cast, and its eerie stage-like atmosphere. Can you believe Lon Chaney was the first choice to play Drac?? Well, in Hitchcock's classic 'Psycho', the blood flowing down the drain during the famous shower scene was chocolate. Did you know it wasn't until Hammer started making their 'Dracula' offerings that the Count was ever filmed in 'living' color--sorry, terrible pun! I found this out in the DK version of the book 'Dracula'.",
  "Yes. Porter had been on death row two years for killing a young couple. After David Protess, a professor of journalism at Northwestern University, and his students re-enacted the crime, Alstory Simon confessed and Porter was set free.",
  "Nope. Sorry, it was Daniel Boone with 30 of his hardy woodsmen that blazed the Trail. By 1800, 200,000 pioneers had travelled the Wilderness Trail going west. Davey Crockett was certainly famous enough in his own right. Remember the Alamo?",
  "Well, you can't take a priceless animal mummy home, but for a donation you can 'adopt' one. The Museum will send you a photo, adoption certificate, and a story about your pet mummy. The money goes to the restoration of the Museum's animal mummies, which is a Good Thing, right? The mummies include crocodiles, ibises, cats, snakes, and dogs. Now you will be the first in your neighborhood to have your own pet mummy. ",
  "When we are born, we have over 300 bones. By the time we reach age 20, some of them have grown together making our skeletons stronger. As adults, we have about 206 bones.",
  "Yes, after 90 people lost their lives when the steamship 'Home' sank off the coast of Ocracoke Island, North Carolina during a hurricane in 1837, the US Congress passed a law that all seagoing ships must carry a life preserver for every passenger.",

  "Olympus Mons, on Mars, is the tallest and widest known volcano. The peak is nearly three times taller than Mt. Everest's. It is entirely out of Mars's atmosphere, and the base is about the size of Missouri. This is a very big volcano!",
  "Orville Wright did crash a plane he was testing for the US Army in 1908 near Ft. Myers, and the Army officer on board, as a passenger, was killed. Wilbur Wright died on May 29, 1912 of typhoid fever when he was 45. Orville died on Jan. 30, 1948.",
  "Remember the old song's words 'stuck a feather in his cap and called it macaroni'? The macaroni penguin has orange feathers on its head, so its name comes from this line of the song.",
  "Yes, indeed! After poring 12 long hours over the cypher, Major Cunningham hopped his horse, rode completely around Union lines and asked the sender 'What does this say?' The Major probably had a few choice words to say that history doesn't record, I bet.",
  "I just made this up off the top of my head. To my knowledge, no such manuscript ever turned up. It would have made interesting reading, yes?",
  "It was Neil Armstrong who made the first footprints on the lunar surface. Remember this, 'That's one small step for man, one giant leap for mankind'?",
  "No, it was Miss Clara Barton who did such wonderful work for Union soldiers in the Civil War, and who founded the American Red Cross. Florence Nightingale was certainly an 'angel of mercy' but not for her work in the American Civil War, but for her work with English soldiers during the Crimean War (1853-1856). ",
  "You have photic sneeze reflex. Photosynthesis is the way plants make food from sunlight.",
  "A crystal of zicron found by Simon Wilde, geologist at Curtin University of Technology in Perth, Australia, was dated at 4.4 billion years old. The Earth itself was only 160 million years old when the crystal was formed. His discovery was made in the outback of Australia. ",
  "Strawberries. Strawberries are known for their antioxidant properties all over, but they are also a rich source of vitamin C. Their vitamin C content is slightly more than that in a single orange.",

  "If you thought that Niagara Falls was large, well, Victoria Falls dwarfs it with its colossal curtain of water that stretches for 1,708 metres, reaching 108 metres in height. It is these epic proportions that make Victoria Falls the largest waterfall in the world.",
  "German historian William Pehle asserts that modern day bowling appears to have its roots in Germany, dating back to 300 CE. At that time, most Germans carried kegels, a wooden, pin-shaped rod for sport and protection, and it was believed that knocking down these kegels, or pins, with a rock would pardon their sins.",
  "The San Diego Zoo is one of the most famous zoos in the world with over 4,000 animals of more than 800 species. The 100 acres (40 ha) of parkland is leased from the City of San Diego.",
  "Harvard opened its doors in 1636. William and Mary College in Virginia opened its doors in 1693.",
  "It has been estimated that the eye muscles move more than 100,000 times a day. Many of these rapid eye movements take place during the dreaming phase of sleep.",
  "The inventor of Kevlar, the lightweight fibre used in bulletproof vests and body armour, has died aged 90. Stephanie Kwolek was a chemist at the DuPont company in Wilmington, Delaware, when she invented the stronger-than-steel fibre in 1965.",
  "The cheetah top speed is around 120 km per hour – by far the fastest land animal in the world, streets ahead of all other wild cats, and the fastest running animal. This fast speed is limited to very short bursts, however, with cheetahs able to sprint at top speed for around 60 seconds only.",
  "Ruminant stomachs have four compartments: the rumen, the reticulum, the omasum and the abomasum. Rumen microbes ferment feed and produce volatile fatty acids, which is the cow's main energy source.",
  "Jamie Farr and Alan Alda were the only two main cast members to have actually served in the U.S. Army in South Korea. Both of them did their tours of duty after the 1953 cease fire. Farr was drafted, serving in Japan at Camp Drake before eventually touring and performing throughout South Korea with friend Red Skelton.",
  "It was directed by Francis Ford Coppola. \"The Godfather Part II\" (1974) and \"The Lord of the Rings: The Return of the King\" (2003)is another film that has won an Oscar for Best Picture.",

  "Many man-made structures can be seen from outer space.",
  "While the UN Conference on International Organization began in San Francisco on 25 April 1945, no headquarters were established at the time.",
  "Shanghai is one of the four direct-administered municipalities of the People's Republic of China ... It has the third-highest number of billionaires of any city in the world and highly ranked institutions including ... the 11th-century Song dynasty, when there was already a river confluence and a town with this name in the area.",
  "Below is a list of the world's biggest countries in terms of area.\n#1 Russia: 17,075,200 km2 (6,591,027 mi2)\n#2 Canada: 9,984,670 km2 (3,854,082 mi2)\n#3 United States: 9,631,418 km2 (3,717,727 mi2)\n#4 China: 9,596,960 km2 (3,704,426 mi2)\n#5 Brazil: 8,511,965 km2 (3,285,618 mi2)",
  "A cygnet is a baby swan. Swans are birds of the family Anatidae within the genus Cygnus. The swans' closest relatives include the geese and ducks. Swans are grouped with the closely related geese in the subfamily Anserinae where they form the tribe Cygnini. Sometimes, they are considered a distinct subfamily, Cygninae.",
  "It's orange and white. Spalding has created the official game ball for the WNBA since the league's first-ever tip-off in 1997. This game-ready basketball has the same multicolor design as the one wielded by legends. Strictly made for the hardwood, its durable composite leather cover is game-ready out of the box.",
  "It actually stands for North Atlantic Treaty Organization. The North Atlantic Treaty Organization, also called the North Atlantic Alliance, is an intergovernmental military alliance between 30 European and North American countries. The organization implements the North Atlantic Treaty that was signed on 4 April 1949.",
  "They had one son, William Lancelot Bowles III, who was born the following year. The marriage ended in 1975. Rashad then married Victor Willis (original lead singer of the Village People, whom she met during the run of The Wiz) in 1978. They divorced in 1982.",
  "In 1999, the Padres and Rockies opened the season in Mexico.",
  "Kangaroo Rat: Believe it or not, this little animal can last longer without drinking water than any other. They go their whole lives (3-5 years) without drinking any! Technically, all these animals have to have water to survive; they just go a very long time without drinking it.",

  "Heinz 57 is a synecdoche of the historical advertising slogan \"57 Varieties\" by the H. J. Heinz Company located in Pittsburgh, Pennsylvania, United States. It has come to mean anything that is made from many parts or origins.",
  "Although popularized by the book 'Peter Pan', the name Wendy has been found in census records from as early as 1881, many years before J.M. Barrie used the name. Some sources indicate that, like Marian and Shirley, it was once a boy's name.",
  "According to legend, somewhere between 1915 and 1921, Chaplin decided to enter a Chaplin look-alike contest, and lost, badly.",
  "He did this 100 years before the moons were even documented.",
  "Nope. Celery has practically no calories... so you burn while you eat it and that's about it.",
  "Actually they had to slow a movie down because he was so fast.",
  "Actually, it took him YEARS to paint the lips.",
  "This was due to the scarcity of metal.",
  "Orange and purple have no words that rhyme... at least, in the dictionary. Yet, brown does have words that rhyme with it.",
  "So far man has exterminated many insects with more than 150 presumed to be missing or extinct. As the study of insect diversity has not been thoroughly examined, there are likely to be hundreds of insects that have become extinct without our knowledge.",

  "This is a true fact, his profit was only about $2.00 a car, but he sold more than 15 million of them.",
  "The hyoid bone in the throat connects to no other bone. Its main function is to support the tongue muscles.",
  "It wasn't Otto Preminger who said that. It was the great Sir Alfred Hitchcock, who said that of Walt Disney.",
  "This is indeed false and it may surprise you that the only number 1 hit Walt Disney ever had on the charts was, \"The Ballad of Davey Crockett\". It held the number 1 position from March 26, 1955 to April 23, 1955. ",
  "Susan Warner and her sister Anna Bartlett Warner are the only two civilians buried in the West Point cemetery. After their father fell on hard times during the Depression, he moved his family to Constitution Island in the Hudson River, opposite West Point. ",
  "There has been one instance where a film and it's sequel were released in the same year. The two movies in question were 'King Kong' and 'Son of Kong', both movies were released in 1933.",
  "GOP was always understood to mean \"grand old party\" although it was once referred to as this \"gallant old party.\" ",
  "All students agree to serve 4 years as a cadet, followed by at least 5 years of active duty (10 if you're a pilot!)",
  "You have to milk 30 ewes to get as much milk as you get from milking one cow.",
  "The Labrador Retriever has been ranked as the most popular breed in the United States by the AKC since 1991; however, it only ranks in third spot across the world. Appearing in three colors (black, yellow or chocolate), the friendly and outgoing personality of a Lab makes them perfectly suited to life as a family pet.",

  "A stalagmite is an upward-growing mound of mineral deposits that have precipitated from water dripping onto the floor of a cave. Most stalagmites have rounded or flattened tips. There are many other types of mineral formations found in caves.",
  "Dublin Dr Pepper was the popular name for a style of Dr Pepper soft drink made by the Dublin Dr Pepper Bottling Company in Dublin, Texas. ... On 12 January 2012, it was announced that Dublin Dr. Pepper will no longer be produced, after ... Though the Dublin plant is not the only Dr Pepper bottler to have used cane sugar ...",
  "Romeo, attempting to restore peace, throws himself between the combatants. Tybalt stabs Mercutio under Romeo's arm, and as Mercutio falls, Tybalt and his men hurry away. Mercutio dies, cursing both the Montagues and the Capulets: “A plague o' both your houses” They fight, and Romeo kills Tybalt.",
  "The US won that one. The 4th Presidents Cup was held between October 19 and 22, 2000. It was played at the Robert Trent Jones Golf Club in Gainesville, Virginia, U.S. The United States team won the competition by a margin of 21​1⁄2–10​1⁄2.",
  "She's on the golden dollar, which appeared in January 2000.Sacagawea was a Lemhi Shoshone woman who, at age 16, met and helped the Lewis and Clark Expedition in achieving their chartered mission objectives by exploring the Louisiana Territory.",
  "The language is Chinese. .3 Billion Native Speakers. Numbers vary widely Ethnologue puts the number of native speakers at 1.3 billion native speakers, roughly 917 million of whom speak Mandarin but there's no doubt it's the most spoken language in the world.",
  "Michael Dell heads Dell Computers. Dell is an American multinational computer technology company that develops, sells, repairs, and supports computers and related products and services. Named after its founder, Michael Dell, the company is one of the largest ... Rollins responded by shifting Dick Hunter from the head of manufacturing to head of customer",
  "The contrabassoon, also known as the double bassoon, is a larger version of the bassoon, sounding an octave lower. Its technique is similar to its smaller cousin, with a few notable differences.",
  "Vladimir Kramnick beat him in the finals! Kasparov reached his peak rating of 2856 on March 3, 2000—at the time an unprecedented number and a record that wasn't broken until Carlsen surpassed it. In 1985 Kasparov defeated Karpov to become the youngest world champion ever at the age of roughly 22 and a half.",

  "A standard guitar has 6 strings.Guitars typically have six strings. Each string has a different thickness. Starting from the thinnest string, the strings are called string 1, string 2, and so on.",
  "Guatemala is located in Central America.Guatemala, a Central American country south of Mexico, is home to volcanoes, rainforests and ancient Mayan sites. The capital, Guatemala City, features the stately National Palace of Culture and the National Museum of Archaeology and Ethnology. Antigua, west of the capital, contains preserved Spanish colonial buildings. Lake Atitlán, formed in a massive volcanic crater, is surrounded by coffee fields and villages.",
  "Ali was featured in several Doritos commercials which were later aired in the Super Bowl. The former Miss USA was also named to People Magazine's '50 Most Beautiful People' in 1998.",
  "Phil Jackson, head coach of the Los Angeles Lakers and former head coach of the Chicago Bulls, led active coaches in total playoff wins.",
  "The ears and the nose are made of cartilage which never stops expanding until death.",
  "The U.S. stock market averaged an 11 percent return per year over the 70 years span",
  "C.C. DeVille (born Bruce Anthony Johannesson; May 14, 1962) is the lead guitarist of the rock band Poison.",
  "'Pleading the 5th' is refusing self-incrimination. In other words, a person chooses not to speak on the grounds that their words may prove them guilty or undermine their case.",
  "APR means annual percentage RATE. It is the yearly rate credit cards charge to their users.",
  "Unfortunately, the number is almost 30 in 100. Smoking, obesity, heredity, lack of exercise, and poor diet all greatly increase the risks associated with getting cancer.",

  "These were the last words spoken by Joan Crawford, on May 10, 1977. They were spoken to her housekeeper, who had started to pray out loud for her. ",
  "George Washington was the first and only President ever elected unanimously.",
  "At 15 years old and inspired by his love of railroads, Walt Disney took a job selling peanuts, popcorn and soda to train passengers.",
  "There were four angels mentioned by name in the King James Bible. They were Gabriel, Michael, Raphael and Lucifer.",
  "A zebra is really black with white stripes. As you look at a zebra the stripes end on it's stomach and inside it's legs. Some zebras are born with hereditary variations that make them mostly dark with white stripes. So as luck would have it zebras have black skin underneath their hair. Ask any zebra. ",
  "She was not only in it, she was the star. Elizabeth June Thornborg is better known as Betty Hutton.",
  "Peter Durand invented the tin can in 1810. The tin can opener was invented by Ezra Warner of Waterbury, Connecticut in 1858.",
  "Ray Brennan was the first person to die from \"legionnaire's disease\" on July 27, 1976. Rainey Bethea, was the last person to be publicly hanged on August 14, 1936 for murder.",
  "Bob Keeshan did indeed play Clarabelle. In 1950, he got got into an argument with producers about his character being used very sparingly and was fired. There was such an outcry from the show's fans that he was hired back and played Clarabelle until 1955. ",
  "Selachophobia is the fear of sharks. Selaphobia is the fear of light flashes.",
  "Yale and Navy were the first colleges to adopt animal mascots. Yale had a bulldog named \"Handsome Dan\" and Navy had a goat named, naturally, \"Billy\".",

  "Alexander the Great was born in Macedonia. He was also known as \"Alexander III\" and was King of Macedonia during the period: 336-323 BC.",
  "Rectangles have opposite equal sides, and their diagonals will always bisect each other.",
  "In 1960, Harper Lee's novel won the Pulitzer Prize.",
  "The Chinese Tiger is very near extinction, whilst the Sumatran, Siberian, and Indian subspecies are also listed as endangered.",
  "Lawn Bowls is a popular outdoor game in which a ball, commonly called the \"bowl\", is rolled along the ground toward a smaller ball, called a \"jack\". ",
  "\"The Disposable Heroes of Hiphoprisy\" were an excellent band which was fronted by Michael Franti. Their album release \"Hypocrisy Is The Greatest Luxury\" included songs such as \"Television the Drug of the Nation\" and \"The Language of Violence.\"",
  "The film was released in 1987. An excellent light-hearted love story about a young princess, pirates and sword-figh",
  "The ship they set out on was the \"Endurance\". Unfortunately the ship got stuck in ice and eventually was crushed under the pressure.",
  "The Lumbar Curve is located in the torso region of the human body.",
  "It was Salvador Dali who painted \"The Persistence of Memory\" in 1931. It featured his famous melting clocks.",
  "St Patrick was born in Kilpatrick, near Dumbarton, in Scotland, in the year 387, according to some sources. Others claim his birthplace to be Wales or England, but no such claim is laid by Ireland.",
  "It has been tried many times over during the ages - to try and turn base metals such as copper into silver or gold. Apparently the process was also meant to help discover a way of prolonging life and a cure for certain diseases. ",
  "Old Kent Road is the cheapest! Mayfair is the highest property that can be bought.",
  "Amethyst is traditionally the gemstone for the month of February.",
  "Douglas Engelbart patented his idea for the computer mouse in the 1950's. His development of this work led to other fields of computing such as the graphical user interface.",

  "The depressed child may pretend to be sick, refuse to go to school, cling to a parent, or worry that the parent may die. Older children may sulk, get into trouble at school, be negative, grouchy, and feel misunderstood.(National Institute of Mental Health)",
  "Depression is so common that over 1 in 5 Americans can expect to get some form of depression in their lifetime. Over 1 in 20 Americans have a depressive disorder every year. Women are almost twice as likely as men to experience a depressive episode throughout their lives. Those who seem to be most likely to experience depression are married women, women in poverty, adolescents, and unmarried men. Fortunately, there are many highly effective treatments for depression today that alleviate much of the suffering associated with depressive symptoms.(National Institute of Mental Health)",
  "Is exercise good for improving your mood? The simple answer can be summed up in two short words: \"Yes, but...\" It's an undisputed \"yes\" if you're in a low mood because of a bad day, and perhaps also if you meet the official criteria for major depression with mild symptoms. However, the \"but\" applies to several factors researchers and therapists are currently working hard to more clearly define",
  "SAD (Seasonal Affective Disorder) is a clinically diagnosed disorder typically characterized by a fall or winter onset with several of the following symptoms:feeling sad or depressed, lethargy, difficulty, concentrating, carbohydrate or sugar cravings (often accompanied by weight gain), difficulty waking in the morning, sleep disturbance, social withdrawal, reduced productivity, and/or irritability. ",
  "You can have depressive illness without really feeling depressed.If you don't feel real depressed or suicidal, but everything else in your life is wrong, you may have unrecognized depressive symptoms.",
  "If you have a gun in your home, you are five times more likely to have a suicide in your house than homes without a gun. ",
  "Schizophrenia distorts the senses, making it very difficult for the individual to tell what is real from what is not real. Whereas Bi-Polars suffer from bouts of manic episodes, ranging from euphoria to irritability.",
  "Bipolar depression, or bipolar disorder, is a biochemical disorder. It's also called \"manic depression.\" A person suffering from bipolar depression experiences depression coupled with manic episodes. The swing from depression into the manic episode is quite marked, and at either pole of emotion the sufferer feels out of control. Manic episodes may last for days, weeks, or even months. In some extreme cases, a patient may switch between mania and depression several times a day. Behaviors during manic episodes vary from euphoria to irritability. Some people experience manic episodes that are characterized by wild swings in thinking, excessive gaiety, exaggerated sexuality, or decreased sleep.",
  "The rates of major depression and dysthymia in women are around double those of men, irrespective of their financial state or race, with the same pattern having been found in several countries. Dysthymia is a chronic depressive illness, lasting for at least two years. ",
  "Some options are: Antidepressants, Psychotherapy/Counseling, Cognitive Therapy, Hormonal, Nutritional, Supplementation, Special Treatment Clinics, Herbal, ECT (Shock Treatments)",
  "Nova Scotia born Captain Slocum commanded some of the finest tall ships ever to sail the seas. On 24th April 1895 he left Boston in his sloop 'Spray' and sailed 46,000 miles around the world, returning to Newport, Rhode Island on 27th June 1898. ",
  "Blushing is a reflex action which develops between the ages of 2 and 4.",
  "The Blue Whale has a disproportionately small eye compared to its body size. The Giant Squid has the largest eye, measuring 400mm across.",
  "The Gordon Bennett Trophy was staged at Athy, Ireland on 2nd July 1903, covering a distance of 327 miles. The previous year the same trophy was competed for with the race being contested over 351 miles between Paris and Innsbruck.",
  "Tea contains more caffeine but, generally, it is more diluted thus having less effect on the body.",
  "The Sudd Swamps are in south central Sudan with its extent varying from 6,370 sq.miles in the dry winter months to approximately 12,350 sq. miles during the summer rains",
  "Stewart Granger was born James Lablanche Stewart in London in 1913. He was forced to change his name in the mid-30s to avoid confusion with the Hollywood star James Stewart. ",
  "The Queen normally faces left, although a few instances of a right-facing monarch have been issued.",
  "Dutch artist Frans Hals' 'Laughing Cavalier' is part of the Wallace Collection in London. Rembrandt, another Dutchman, painted 'The Night Watch' which is on display at the Rijksmuseum, Amsterdam. ",
  "Tae kwon do comes from Korea.",
  "In 1783 a duck, a sheep and a rooster safely underwent an eight-minute flight in a balloon built by the Montgolfier brothers.",
  "Mike Hawthorn was the first Brit to win the motor racing World Championship in 1958.",
  "This popular misconception came about following a misplaced decimal point in a set of food tables published in 1870. Vegetables, generally, contain the same amount of iron.",
  "Some sources cite Edmund Spenser as first Poet Laureate (1591-99), while others say that Ben Jonson was the first 'real' holder of the post (1619-37). The first official laureate was John Dryden (1668-89). Shakespeare never held the position.",
  "Czar Alexander III (Emperor of Russia 1881-94) drew up plans for the railway. It runs for almost 6,000 miles from Moscow to Vladivostok, the original route. 3 additional routes have since been added.",
  "Unfortunately there are still people today who believe this to be true but, unlike a passing bad mood, depression is an illness that involves the mind, body and thoughts. If left untreated it can cause serious problems to sufferers and people around them.",
  "There are several types of depression ranging from mild to disabling. Some of the milder forms are treatable with some counseling. More severe forms may call for medication and even hospitalization.",
  "Some types of depression run in families, suggesting that a biological vulnerability can be inherited. This seems to be the case with bipolar disorder. Studies of families in which members of each generation develop bipolar disorder found that those with the illness have a somewhat different genetic makeup than those who do not get ill. ",
  "Until recent years men saw emotions as womanly and weak, some men still feel this way and are less likely to admit depression. Some will cover it up with activities such as drinking, drugs or overworking.",
  "Although sedatives may sometimes be prescribed along with antidepressants they are not the same thing. Most antidepressants affect a chemical imbalance in the brain, while sedatives are used to calm. Sedatives alone are not an effective antidepressant."

};

char answers[195] = {
   'T','T','T','T','T','T','T','T','T','F',
   'T','F','F','T','T','T','T','T','F','T',
   'T','T','T','T','T','T','T','F','T','T',
   'F','T','F','T','F','T','F','T','F','F',
   'F','F','F','F','F','F','F','F','F','T',
   'T','T','T','T','F','F','F','F','F','F',
   'F','T','F','T','F','T','F','T','F','T',
   'T','F','T','T','F','F','F','F','T','T',
   'F','F','F','T','F','T','F','T','T','T',
   'F','F','T','T','F','F','F','T','F','T',
   'F','F','F','T','F','F','F','T','T','F',
   'T','F','F','F','F','F','F','T','T','F',
   'F','F','F','F','F','T','F','F','F','F',
   'F','T','F','T','F','T','F','F','F','F',
   'F','T','F','F','T','T','F','T','F','F',
   'T','T','T','F','T','T','F','T','F','F',
   'T','T','F','F','F','F','T','T','T','F',
   'T','F','T','T','T','T','T','F','T','F',
   'T','T','F','F','F','T','F','F','F','T',
   'F','T','T','F','F'
  };

};

#endif // TRUEORFALSEQUESTIONS_H
